// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

static const u16 sLeafingEggMoveLearnset[] = {
    MOVE_LEECH_SEED,
    MOVE_SYNTHESIS,
    MOVE_GRASS_WHISTLE,
    MOVE_METAL_SOUND,
    MOVE_UNAVAILABLE,
};

