// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

const u32 gMonFrontPic_Leafing[] = INCGFX_U32("graphics/pokemon/sigma/leafing/anim_front.png", ".4bpp.smol");
const u16 gMonPalette_Leafing[] = INCGFX_U16("graphics/pokemon/sigma/leafing/normal.pal", ".gbapal");
const u16 gMonShinyPalette_Leafing[] = INCGFX_U16("graphics/pokemon/sigma/leafing/shiny.pal", ".gbapal");
const u8 gMonIcon_Leafing[] = INCGFX_U8("graphics/pokemon/sigma/leafing/icon.png", ".4bpp");
const u32 gMonBackPic_Leafing[] = INCGFX_U32("graphics/pokemon/sigma/leafing/back.png", ".4bpp.smol");

