// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

static const struct LevelUpMove sLeafingLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_TACKLE),
    LEVEL_UP_MOVE( 1, MOVE_LEER),
    LEVEL_UP_MOVE( 6, MOVE_ABSORB),
    LEVEL_UP_MOVE(10, MOVE_FURY_CUTTER),
    LEVEL_UP_MOVE(15, MOVE_RAZOR_LEAF),
    LEVEL_UP_MOVE(20, MOVE_METAL_CLAW),
    LEVEL_UP_MOVE(25, MOVE_MEGA_DRAIN),
    LEVEL_UP_MOVE(30, MOVE_SLASH),
    LEVEL_UP_MOVE(35, MOVE_IRON_DEFENSE),
    LEVEL_UP_MOVE(40, MOVE_LEAF_BLADE),
    LEVEL_UP_MOVE(45, MOVE_SWORDS_DANCE),
    LEVEL_UP_END
};

static const struct LevelUpMove sLeafsteelLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_SLASH),
    LEVEL_UP_END
};

static const struct LevelUpMove sLeafaxerLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_LEAF_BLADE),
    LEVEL_UP_MOVE(40, MOVE_IRON_TAIL),
    LEVEL_UP_MOVE(60, MOVE_BEHEMOTH_BLADE),
    LEVEL_UP_END
};

static const struct LevelUpMove sWealtherLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_FEINT_ATTACK),
    LEVEL_UP_END
};

static const struct LevelUpMove sWarrallierLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_FLIP_TURN),
    LEVEL_UP_END
};

static const struct LevelUpMove sHeatbatLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_AIR_SLASH),
    LEVEL_UP_END
};

static const struct LevelUpMove sBlazterraLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_HEAT_WAVE),
    LEVEL_UP_END
};

static const struct LevelUpMove sToxirenLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_HYPER_VOICE),
    LEVEL_UP_END
};

static const struct LevelUpMove sSigmaulerLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_HAMMER_ARM),
    LEVEL_UP_END
};

static const struct LevelUpMove sMotinkyLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_FIRE_SPIN),
    LEVEL_UP_END
};

static const struct LevelUpMove sGortikiLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_FIERY_DANCE),
    LEVEL_UP_END
};

static const struct LevelUpMove sDevampryLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_HYPER_VOICE),
    LEVEL_UP_END
};

static const struct LevelUpMove sGalfrogtomLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_DISCHARGE),
    LEVEL_UP_END
};

static const struct LevelUpMove sJanenonLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_DARK_PULSE),
    LEVEL_UP_END
};

static const struct LevelUpMove sBlylemLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_STEALTH_ROCK),
    LEVEL_UP_END
};

