// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

static const struct LevelUpMove sLeafingLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_TACKLE),
    LEVEL_UP_MOVE( 1, MOVE_LEER),
    LEVEL_UP_MOVE( 6, MOVE_ABSORB),
    LEVEL_UP_MOVE(10, MOVE_FURY_CUTTER),
    LEVEL_UP_MOVE(15, MOVE_RAZOR_LEAF),
    LEVEL_UP_MOVE(20, MOVE_METAL_CLAW),
    LEVEL_UP_MOVE(25, MOVE_MEGA_DRAIN),
    LEVEL_UP_MOVE(30, MOVE_SLASH),
    LEVEL_UP_MOVE(35, MOVE_IRON_DEFENSE),
    LEVEL_UP_MOVE(40, MOVE_LEAF_BLADE),
    LEVEL_UP_MOVE(45, MOVE_SWORDS_DANCE),
    LEVEL_UP_END
};

static const struct LevelUpMove sLeafsteelLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_SLASH),
    LEVEL_UP_END
};

static const struct LevelUpMove sLeafaxerLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_LEAF_BLADE),
    LEVEL_UP_MOVE(40, MOVE_IRON_TAIL),
    LEVEL_UP_MOVE(60, MOVE_BEHEMOTH_BLADE),
    LEVEL_UP_END
};

