// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

#include "global.h"
#include "pokemon.h"
#include "test/battle.h"
#include "constants/characters.h"

TEST("Sigma dex: Leafing has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_LEAFING];
    EXPECT_EQ(info->baseHP, 45);
    EXPECT_EQ(info->baseAttack, 60);
    EXPECT_EQ(info->baseDefense, 55);
    EXPECT_EQ(info->baseSpeed, 55);
    EXPECT_EQ(info->baseSpAttack, 45);
    EXPECT_EQ(info->baseSpDefense, 50);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_GRASS);
    EXPECT_EQ(info->abilities[0], ABILITY_OVERGROW);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_TACKLE);
    EXPECT_EQ(GetSpeciesName(SPECIES_LEAFING)[0], CHAR_L);
}

SINGLE_BATTLE_TEST("Sigma dex: Leafing can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_LEAFING) { Moves(MOVE_TACKLE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_TACKLE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, player);
    }
}

