// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

#include "global.h"
#include "pokemon.h"
#include "test/battle.h"
#include "constants/characters.h"

TEST("Sigma dex: Leafing has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_LEAFING];
    EXPECT_EQ(info->baseHP, 60);
    EXPECT_EQ(info->baseAttack, 65);
    EXPECT_EQ(info->baseDefense, 60);
    EXPECT_EQ(info->baseSpeed, 40);
    EXPECT_EQ(info->baseSpAttack, 45);
    EXPECT_EQ(info->baseSpDefense, 50);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_GRASS);
    EXPECT_EQ(info->abilities[0], ABILITY_OVERGROW);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_TACKLE);
    EXPECT_EQ(GetSpeciesName(SPECIES_LEAFING)[0], CHAR_L);
}

SINGLE_BATTLE_TEST("Sigma dex: Leafing can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_LEAFING) { Moves(MOVE_TACKLE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_TACKLE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, player);
    }
}

TEST("Sigma dex: Leafsteel has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_LEAFSTEEL];
    EXPECT_EQ(info->baseHP, 75);
    EXPECT_EQ(info->baseAttack, 90);
    EXPECT_EQ(info->baseDefense, 80);
    EXPECT_EQ(info->baseSpeed, 50);
    EXPECT_EQ(info->baseSpAttack, 60);
    EXPECT_EQ(info->baseSpDefense, 65);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_STEEL);
    EXPECT_EQ(info->abilities[0], ABILITY_OVERGROW);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_SLASH);
    EXPECT_EQ(GetSpeciesName(SPECIES_LEAFSTEEL)[0], CHAR_L);
}

SINGLE_BATTLE_TEST("Sigma dex: Leafsteel can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_LEAFSTEEL) { Moves(MOVE_SLASH); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_SLASH); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SLASH, player);
    }
}

TEST("Sigma dex: Leafaxer has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_LEAFAXER];
    EXPECT_EQ(info->baseHP, 90);
    EXPECT_EQ(info->baseAttack, 130);
    EXPECT_EQ(info->baseDefense, 100);
    EXPECT_EQ(info->baseSpeed, 60);
    EXPECT_EQ(info->baseSpAttack, 70);
    EXPECT_EQ(info->baseSpDefense, 80);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_STEEL);
    EXPECT_EQ(info->abilities[0], ABILITY_OVERGROW);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_LEAF_BLADE);
    EXPECT_EQ(GetSpeciesName(SPECIES_LEAFAXER)[0], CHAR_L);
}

SINGLE_BATTLE_TEST("Sigma dex: Leafaxer can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_LEAFAXER) { Moves(MOVE_LEAF_BLADE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_LEAF_BLADE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_LEAF_BLADE, player);
    }
}

TEST("Sigma dex: Waffy has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_WAFFY];
    EXPECT_EQ(info->baseHP, 55);
    EXPECT_EQ(info->baseAttack, 65);
    EXPECT_EQ(info->baseDefense, 50);
    EXPECT_EQ(info->baseSpeed, 55);
    EXPECT_EQ(info->baseSpAttack, 45);
    EXPECT_EQ(info->baseSpDefense, 50);
    EXPECT_EQ(info->types[0], TYPE_WATER);
    EXPECT_EQ(info->types[1], TYPE_WATER);
    EXPECT_EQ(info->abilities[0], ABILITY_TORRENT);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_TACKLE);
    EXPECT_EQ(GetSpeciesName(SPECIES_WAFFY)[0], CHAR_W);
}

SINGLE_BATTLE_TEST("Sigma dex: Waffy can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_WAFFY) { Moves(MOVE_TACKLE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_TACKLE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, player);
    }
}

TEST("Sigma dex: Wealther has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_WEALTHER];
    EXPECT_EQ(info->baseHP, 65);
    EXPECT_EQ(info->baseAttack, 85);
    EXPECT_EQ(info->baseDefense, 65);
    EXPECT_EQ(info->baseSpeed, 80);
    EXPECT_EQ(info->baseSpAttack, 65);
    EXPECT_EQ(info->baseSpDefense, 60);
    EXPECT_EQ(info->types[0], TYPE_WATER);
    EXPECT_EQ(info->types[1], TYPE_DARK);
    EXPECT_EQ(info->abilities[0], ABILITY_TORRENT);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_HONE_CLAWS);
    EXPECT_EQ(GetSpeciesName(SPECIES_WEALTHER)[0], CHAR_W);
}

SINGLE_BATTLE_TEST("Sigma dex: Wealther can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_WEALTHER) { Moves(MOVE_HONE_CLAWS); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_HONE_CLAWS); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HONE_CLAWS, player);
    }
}

TEST("Sigma dex: Warrallier has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_WARRALLIER];
    EXPECT_EQ(info->baseHP, 80);
    EXPECT_EQ(info->baseAttack, 115);
    EXPECT_EQ(info->baseDefense, 75);
    EXPECT_EQ(info->baseSpeed, 105);
    EXPECT_EQ(info->baseSpAttack, 80);
    EXPECT_EQ(info->baseSpDefense, 75);
    EXPECT_EQ(info->types[0], TYPE_WATER);
    EXPECT_EQ(info->types[1], TYPE_DARK);
    EXPECT_EQ(info->abilities[0], ABILITY_TORRENT);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_FLIP_TURN);
    EXPECT_EQ(GetSpeciesName(SPECIES_WARRALLIER)[0], CHAR_W);
}

SINGLE_BATTLE_TEST("Sigma dex: Warrallier can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_WARRALLIER) { Moves(MOVE_FLIP_TURN); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_FLIP_TURN); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_FLIP_TURN, player);
    }
}

TEST("Sigma dex: Torchbat has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_TORCHBAT];
    EXPECT_EQ(info->baseHP, 45);
    EXPECT_EQ(info->baseAttack, 50);
    EXPECT_EQ(info->baseDefense, 45);
    EXPECT_EQ(info->baseSpeed, 70);
    EXPECT_EQ(info->baseSpAttack, 60);
    EXPECT_EQ(info->baseSpDefense, 50);
    EXPECT_EQ(info->types[0], TYPE_FIRE);
    EXPECT_EQ(info->types[1], TYPE_FIRE);
    EXPECT_EQ(info->abilities[0], ABILITY_BLAZE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_SCRATCH);
    EXPECT_EQ(GetSpeciesName(SPECIES_TORCHBAT)[0], CHAR_T);
}

SINGLE_BATTLE_TEST("Sigma dex: Torchbat can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_TORCHBAT) { Moves(MOVE_SCRATCH); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_SCRATCH); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, player);
    }
}

TEST("Sigma dex: Heatbat has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_HEATBAT];
    EXPECT_EQ(info->baseHP, 60);
    EXPECT_EQ(info->baseAttack, 65);
    EXPECT_EQ(info->baseDefense, 60);
    EXPECT_EQ(info->baseSpeed, 85);
    EXPECT_EQ(info->baseSpAttack, 85);
    EXPECT_EQ(info->baseSpDefense, 65);
    EXPECT_EQ(info->types[0], TYPE_FIRE);
    EXPECT_EQ(info->types[1], TYPE_FIRE);
    EXPECT_EQ(info->abilities[0], ABILITY_BLAZE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_AIR_SLASH);
    EXPECT_EQ(GetSpeciesName(SPECIES_HEATBAT)[0], CHAR_H);
}

SINGLE_BATTLE_TEST("Sigma dex: Heatbat can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_HEATBAT) { Moves(MOVE_AIR_SLASH); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_AIR_SLASH); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_AIR_SLASH, player);
    }
}

TEST("Sigma dex: Blazterra has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_BLAZTERRA];
    EXPECT_EQ(info->baseHP, 70);
    EXPECT_EQ(info->baseAttack, 85);
    EXPECT_EQ(info->baseDefense, 75);
    EXPECT_EQ(info->baseSpeed, 120);
    EXPECT_EQ(info->baseSpAttack, 105);
    EXPECT_EQ(info->baseSpDefense, 75);
    EXPECT_EQ(info->types[0], TYPE_FIRE);
    EXPECT_EQ(info->types[1], TYPE_FLYING);
    EXPECT_EQ(info->abilities[0], ABILITY_BLAZE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_HEAT_WAVE);
    EXPECT_EQ(GetSpeciesName(SPECIES_BLAZTERRA)[0], CHAR_B);
}

SINGLE_BATTLE_TEST("Sigma dex: Blazterra can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_BLAZTERRA) { Moves(MOVE_HEAT_WAVE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_HEAT_WAVE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HEAT_WAVE, player);
    }
}

TEST("Sigma dex: Lapper has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_LAPPER];
    EXPECT_EQ(info->baseHP, 60);
    EXPECT_EQ(info->baseAttack, 75);
    EXPECT_EQ(info->baseDefense, 45);
    EXPECT_EQ(info->baseSpeed, 67);
    EXPECT_EQ(info->baseSpAttack, 25);
    EXPECT_EQ(info->baseSpDefense, 55);
    EXPECT_EQ(info->types[0], TYPE_NORMAL);
    EXPECT_EQ(info->types[1], TYPE_FIGHTING);
    EXPECT_EQ(info->abilities[0], ABILITY_SCRAPPY);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_TACKLE);
    EXPECT_EQ(GetSpeciesName(SPECIES_LAPPER)[0], CHAR_L);
}

SINGLE_BATTLE_TEST("Sigma dex: Lapper can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_LAPPER) { Moves(MOVE_TACKLE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_TACKLE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, player);
    }
}

TEST("Sigma dex: Brawleo has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_BRAWLEO];
    EXPECT_EQ(info->baseHP, 80);
    EXPECT_EQ(info->baseAttack, 110);
    EXPECT_EQ(info->baseDefense, 67);
    EXPECT_EQ(info->baseSpeed, 103);
    EXPECT_EQ(info->baseSpAttack, 45);
    EXPECT_EQ(info->baseSpDefense, 80);
    EXPECT_EQ(info->types[0], TYPE_NORMAL);
    EXPECT_EQ(info->types[1], TYPE_FIGHTING);
    EXPECT_EQ(info->abilities[0], ABILITY_SCRAPPY);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_MACH_PUNCH);
    EXPECT_EQ(GetSpeciesName(SPECIES_BRAWLEO)[0], CHAR_B);
}

SINGLE_BATTLE_TEST("Sigma dex: Brawleo can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_BRAWLEO) { Moves(MOVE_MACH_PUNCH); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_MACH_PUNCH); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_MACH_PUNCH, player);
    }
}

TEST("Sigma dex: Galfrogtom has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_GALFROGTOM];
    EXPECT_EQ(info->baseHP, 59);
    EXPECT_EQ(info->baseAttack, 89);
    EXPECT_EQ(info->baseDefense, 49);
    EXPECT_EQ(info->baseSpeed, 119);
    EXPECT_EQ(info->baseSpAttack, 139);
    EXPECT_EQ(info->baseSpDefense, 49);
    EXPECT_EQ(info->types[0], TYPE_GHOST);
    EXPECT_EQ(info->types[1], TYPE_ELECTRIC);
    EXPECT_EQ(info->abilities[0], ABILITY_CLEAR_BODY);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_DISCHARGE);
    EXPECT_EQ(GetSpeciesName(SPECIES_GALFROGTOM)[0], CHAR_G);
}

SINGLE_BATTLE_TEST("Sigma dex: Galfrogtom can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_GALFROGTOM) { Moves(MOVE_DISCHARGE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_DISCHARGE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_DISCHARGE, player);
    }
}

TEST("Sigma dex: Toxiren has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_TOXIREN];
    EXPECT_EQ(info->baseHP, 94);
    EXPECT_EQ(info->baseAttack, 52);
    EXPECT_EQ(info->baseDefense, 69);
    EXPECT_EQ(info->baseSpeed, 35);
    EXPECT_EQ(info->baseSpAttack, 110);
    EXPECT_EQ(info->baseSpDefense, 140);
    EXPECT_EQ(info->types[0], TYPE_POISON);
    EXPECT_EQ(info->types[1], TYPE_FAIRY);
    EXPECT_EQ(info->abilities[0], ABILITY_LIQUID_OOZE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_HYPER_VOICE);
    EXPECT_EQ(GetSpeciesName(SPECIES_TOXIREN)[0], CHAR_T);
}

SINGLE_BATTLE_TEST("Sigma dex: Toxiren can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_TOXIREN) { Moves(MOVE_HYPER_VOICE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_HYPER_VOICE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HYPER_VOICE, player);
    }
}

TEST("Sigma dex: Sigmauler has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_SIGMAULER];
    EXPECT_EQ(info->baseHP, 100);
    EXPECT_EQ(info->baseAttack, 100);
    EXPECT_EQ(info->baseDefense, 167);
    EXPECT_EQ(info->baseSpeed, 21);
    EXPECT_EQ(info->baseSpAttack, 55);
    EXPECT_EQ(info->baseSpDefense, 67);
    EXPECT_EQ(info->types[0], TYPE_ROCK);
    EXPECT_EQ(info->types[1], TYPE_FIGHTING);
    EXPECT_EQ(info->abilities[0], ABILITY_STURDY);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_HAMMER_ARM);
    EXPECT_EQ(GetSpeciesName(SPECIES_SIGMAULER)[0], CHAR_S);
}

SINGLE_BATTLE_TEST("Sigma dex: Sigmauler can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_SIGMAULER) { Moves(MOVE_HAMMER_ARM); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_HAMMER_ARM); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HAMMER_ARM, player);
    }
}

TEST("Sigma dex: Tinky has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_TINKY];
    EXPECT_EQ(info->baseHP, 35);
    EXPECT_EQ(info->baseAttack, 30);
    EXPECT_EQ(info->baseDefense, 65);
    EXPECT_EQ(info->baseSpeed, 50);
    EXPECT_EQ(info->baseSpAttack, 55);
    EXPECT_EQ(info->baseSpDefense, 50);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_GRASS);
    EXPECT_EQ(info->abilities[0], ABILITY_HEATPROOF);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_ABSORB);
    EXPECT_EQ(GetSpeciesName(SPECIES_TINKY)[0], CHAR_T);
}

SINGLE_BATTLE_TEST("Sigma dex: Tinky can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_TINKY) { Moves(MOVE_ABSORB); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_ABSORB); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ABSORB, player);
    }
}

TEST("Sigma dex: Motinky has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_MOTINKY];
    EXPECT_EQ(info->baseHP, 55);
    EXPECT_EQ(info->baseAttack, 42);
    EXPECT_EQ(info->baseDefense, 91);
    EXPECT_EQ(info->baseSpeed, 72);
    EXPECT_EQ(info->baseSpAttack, 90);
    EXPECT_EQ(info->baseSpDefense, 70);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_FIRE);
    EXPECT_EQ(info->abilities[0], ABILITY_FLASH_FIRE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_FIRE_SPIN);
    EXPECT_EQ(GetSpeciesName(SPECIES_MOTINKY)[0], CHAR_M);
}

SINGLE_BATTLE_TEST("Sigma dex: Motinky can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_MOTINKY) { Moves(MOVE_FIRE_SPIN); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_FIRE_SPIN); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_FIRE_SPIN, player);
    }
}

TEST("Sigma dex: Gortiki has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_GORTIKI];
    EXPECT_EQ(info->baseHP, 80);
    EXPECT_EQ(info->baseAttack, 67);
    EXPECT_EQ(info->baseDefense, 110);
    EXPECT_EQ(info->baseSpeed, 72);
    EXPECT_EQ(info->baseSpAttack, 108);
    EXPECT_EQ(info->baseSpDefense, 93);
    EXPECT_EQ(info->types[0], TYPE_GRASS);
    EXPECT_EQ(info->types[1], TYPE_FIRE);
    EXPECT_EQ(info->abilities[0], ABILITY_FLASH_FIRE);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_FIERY_DANCE);
    EXPECT_EQ(GetSpeciesName(SPECIES_GORTIKI)[0], CHAR_G);
}

SINGLE_BATTLE_TEST("Sigma dex: Gortiki can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_GORTIKI) { Moves(MOVE_FIERY_DANCE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_FIERY_DANCE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_FIERY_DANCE, player);
    }
}

TEST("Sigma dex: Devampry has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_DEVAMPRY];
    EXPECT_EQ(info->baseHP, 82);
    EXPECT_EQ(info->baseAttack, 75);
    EXPECT_EQ(info->baseDefense, 69);
    EXPECT_EQ(info->baseSpeed, 95);
    EXPECT_EQ(info->baseSpAttack, 95);
    EXPECT_EQ(info->baseSpDefense, 87);
    EXPECT_EQ(info->types[0], TYPE_NORMAL);
    EXPECT_EQ(info->types[1], TYPE_DARK);
    EXPECT_EQ(info->abilities[0], ABILITY_SOUNDPROOF);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_HYPER_VOICE);
    EXPECT_EQ(GetSpeciesName(SPECIES_DEVAMPRY)[0], CHAR_D);
}

SINGLE_BATTLE_TEST("Sigma dex: Devampry can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_DEVAMPRY) { Moves(MOVE_HYPER_VOICE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_HYPER_VOICE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HYPER_VOICE, player);
    }
}

TEST("Sigma dex: Janenon has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_JANENON];
    EXPECT_EQ(info->baseHP, 46);
    EXPECT_EQ(info->baseAttack, 67);
    EXPECT_EQ(info->baseDefense, 100);
    EXPECT_EQ(info->baseSpeed, 25);
    EXPECT_EQ(info->baseSpAttack, 167);
    EXPECT_EQ(info->baseSpDefense, 85);
    EXPECT_EQ(info->types[0], TYPE_DARK);
    EXPECT_EQ(info->types[1], TYPE_FAIRY);
    EXPECT_EQ(info->abilities[0], ABILITY_TANGLING_HAIR);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_DARK_PULSE);
    EXPECT_EQ(GetSpeciesName(SPECIES_JANENON)[0], CHAR_J);
}

SINGLE_BATTLE_TEST("Sigma dex: Janenon can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_JANENON) { Moves(MOVE_DARK_PULSE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_DARK_PULSE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_DARK_PULSE, player);
    }
}

TEST("Sigma dex: Blylem has the data from its species file")
{
    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_BLYLEM];
    EXPECT_EQ(info->baseHP, 81);
    EXPECT_EQ(info->baseAttack, 67);
    EXPECT_EQ(info->baseDefense, 102);
    EXPECT_EQ(info->baseSpeed, 20);
    EXPECT_EQ(info->baseSpAttack, 125);
    EXPECT_EQ(info->baseSpDefense, 130);
    EXPECT_EQ(info->types[0], TYPE_ROCK);
    EXPECT_EQ(info->types[1], TYPE_POISON);
    EXPECT_EQ(info->abilities[0], ABILITY_STURDY);
    EXPECT_EQ(info->levelUpLearnset[0].move, MOVE_STEALTH_ROCK);
    EXPECT_EQ(GetSpeciesName(SPECIES_BLYLEM)[0], CHAR_B);
}

SINGLE_BATTLE_TEST("Sigma dex: Blylem can use its first move in battle")
{
    GIVEN {
        PLAYER(SPECIES_BLYLEM) { Moves(MOVE_STEALTH_ROCK); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_STEALTH_ROCK); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_STEALTH_ROCK, player);
    }
}

