// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

    SPECIES_LEAFING,
    SPECIES_LEAFSTEEL,
    SPECIES_LEAFAXER,
    SPECIES_WEALTHER,
    SPECIES_WARRALLIER,
    SPECIES_BLAZTERRA,
