// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

    [SPECIES_LEAFING] =
    {
        .baseHP = 45,
        .baseAttack = 60,
        .baseDefense = 55,
        .baseSpeed = 55,
        .baseSpAttack = 45,
        .baseSpDefense = 50,
        .types = MON_TYPES(TYPE_GRASS),
        .catchRate = 45,
        .expYield = 64,
        .evYield_Attack = 1,
        .genderRatio = PERCENT_FEMALE(12.5),
        .eggCycles = 20,
        .friendship = STANDARD_FRIENDSHIP,
        .growthRate = GROWTH_MEDIUM_SLOW,
        .eggGroups = MON_EGG_GROUPS(EGG_GROUP_FIELD, EGG_GROUP_GRASS),
        .abilities = { ABILITY_OVERGROW, ABILITY_NONE, ABILITY_NONE },
        .bodyColor = BODY_COLOR_GREEN,
        .speciesName = _("Leafing"),
        .cryId = CRY_NONE,
        .natDexNum = NATIONAL_DEX_LEAFING,
        .categoryName = _("Sprout"),
        .height = 5,
        .weight = 58,
        .description = COMPOUND_STRING(
            "LEAFING hides among fallen leaves to\n"
            "nap in the sun. The leaf on its head\n"
            "hardens a little each time it battles,\n"
            "until the edge shines like metal."),
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
        .frontPic = gMonFrontPic_CircledQuestionMark,
        .frontPicSize = MON_COORDS_SIZE(64, 64),
        .frontPicYOffset = 0,
        .frontAnimFrames = sAnims_SingleFramePlaceHolder,
        .backPic = gMonBackPic_CircledQuestionMark,
        .backPicSize = MON_COORDS_SIZE(64, 64),
        .backPicYOffset = 7,
        .backAnimId = BACK_ANIM_NONE,
        .palette = gMonPalette_CircledQuestionMark,
        .shinyPalette = gMonShinyPalette_CircledQuestionMark,
        .iconSprite = gMonIcon_QuestionMark,
        .iconPalIndex = 0,
        .levelUpLearnset = sLeafingLevelUpLearnset,
        .teachableLearnset = sLeafingTeachableLearnset,
        .eggMoveLearnset = sLeafingEggMoveLearnset,
        FOOTPRINT(QuestionMark)
    },

