// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.

static const u16 sLeafingTeachableLearnset[] = {
    MOVE_DRAGON_CLAW,
    MOVE_TOXIC,
    MOVE_BULLET_SEED,
    MOVE_HIDDEN_POWER,
    MOVE_SUNNY_DAY,
    MOVE_PROTECT,
    MOVE_GIGA_DRAIN,
    MOVE_FRUSTRATION,
    MOVE_SOLAR_BEAM,
    MOVE_IRON_TAIL,
    MOVE_RETURN,
    MOVE_DOUBLE_TEAM,
    MOVE_AERIAL_ACE,
    MOVE_FACADE,
    MOVE_SECRET_POWER,
    MOVE_REST,
    MOVE_ATTRACT,
    MOVE_CUT,
    MOVE_STRENGTH,
    MOVE_FLASH,
    MOVE_ROCK_SMASH,
    MOVE_SWORDS_DANCE,
    MOVE_BODY_SLAM,
    MOVE_DOUBLE_EDGE,
    MOVE_MIMIC,
    MOVE_SUBSTITUTE,
    MOVE_SNORE,
    MOVE_ENDURE,
    MOVE_MUD_SLAP,
    MOVE_SWAGGER,
    MOVE_SLEEP_TALK,
    MOVE_FURY_CUTTER,
    MOVE_UNAVAILABLE,
};

static const u16 sLeafsteelTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sLeafaxerTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sWealtherTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sWarrallierTeachableLearnset[] = {
    MOVE_FOCUS_PUNCH,
    MOVE_WATER_PULSE,
    MOVE_TOXIC,
    MOVE_BULK_UP,
    MOVE_HIDDEN_POWER,
    MOVE_TAUNT,
    MOVE_ICE_BEAM,
    MOVE_PROTECT,
    MOVE_RAIN_DANCE,
    MOVE_FRUSTRATION,
    MOVE_IRON_TAIL,
    MOVE_BRICK_BREAK,
    MOVE_DOUBLE_TEAM,
    MOVE_TORMENT,
    MOVE_FACADE,
    MOVE_THIEF,
    MOVE_SNATCH,
    MOVE_CUT,
    MOVE_SURF,
    MOVE_STRENGTH,
    MOVE_ROCK_SMASH,
    MOVE_WATERFALL,
    MOVE_DIVE,
    MOVE_UNAVAILABLE,
};

static const u16 sHeatbatTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sBlazterraTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sSigmaulerTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMotinkyTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sGortikiTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sGalfrogtomTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sJanenonTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sBlylemTeachableLearnset[] = {
    MOVE_UNAVAILABLE,
};

