// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/pokemon/egg_moves.h

    egg_moves(LEAFING,
              MOVE_LEECH_SEED,
              MOVE_SYNTHESIS,
              MOVE_GRASS_WHISTLE,
              MOVE_METAL_SOUND),

