// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/graphics/pokemon.h (and the image files into graphics/pokemon/<name>/)

const u32 gMonStillFrontPic_Leafing[] = INCGFX_U32("graphics/pokemon/leafing/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Leafing[] = INCGFX_U32("graphics/pokemon/leafing/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Leafing[] = INCGFX_U32("graphics/pokemon/leafing/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Leafing[] = INCGFX_U32("graphics/pokemon/leafing/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Leafing[] = INCGFX_U32("graphics/pokemon/leafing/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Leafing[] = INCGFX_U8("graphics/pokemon/leafing/icon.png", ".4bpp");
const u8 gMonFootprint_Leafing[] = INCGFX_U8("graphics/pokemon/leafing/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Leafsteel[] = INCGFX_U32("graphics/pokemon/leafsteel/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Leafsteel[] = INCGFX_U32("graphics/pokemon/leafsteel/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Leafsteel[] = INCGFX_U32("graphics/pokemon/leafsteel/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Leafsteel[] = INCGFX_U32("graphics/pokemon/leafsteel/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Leafsteel[] = INCGFX_U32("graphics/pokemon/leafsteel/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Leafsteel[] = INCGFX_U8("graphics/pokemon/leafsteel/icon.png", ".4bpp");
const u8 gMonFootprint_Leafsteel[] = INCGFX_U8("graphics/pokemon/leafsteel/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Leafaxer[] = INCGFX_U32("graphics/pokemon/leafaxer/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Leafaxer[] = INCGFX_U32("graphics/pokemon/leafaxer/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Leafaxer[] = INCGFX_U32("graphics/pokemon/leafaxer/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Leafaxer[] = INCGFX_U32("graphics/pokemon/leafaxer/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Leafaxer[] = INCGFX_U32("graphics/pokemon/leafaxer/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Leafaxer[] = INCGFX_U8("graphics/pokemon/leafaxer/icon.png", ".4bpp");
const u8 gMonFootprint_Leafaxer[] = INCGFX_U8("graphics/pokemon/leafaxer/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Waffy[] = INCGFX_U32("graphics/pokemon/waffy/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Waffy[] = INCGFX_U32("graphics/pokemon/waffy/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Waffy[] = INCGFX_U32("graphics/pokemon/waffy/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Waffy[] = INCGFX_U32("graphics/pokemon/waffy/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Waffy[] = INCGFX_U32("graphics/pokemon/waffy/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Waffy[] = INCGFX_U8("graphics/pokemon/waffy/icon.png", ".4bpp");
const u8 gMonFootprint_Waffy[] = INCGFX_U8("graphics/pokemon/waffy/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Wealther[] = INCGFX_U32("graphics/pokemon/wealther/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Wealther[] = INCGFX_U32("graphics/pokemon/wealther/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Wealther[] = INCGFX_U32("graphics/pokemon/wealther/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Wealther[] = INCGFX_U32("graphics/pokemon/wealther/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Wealther[] = INCGFX_U32("graphics/pokemon/wealther/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Wealther[] = INCGFX_U8("graphics/pokemon/wealther/icon.png", ".4bpp");
const u8 gMonFootprint_Wealther[] = INCGFX_U8("graphics/pokemon/wealther/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Warrallier[] = INCGFX_U32("graphics/pokemon/warrallier/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Warrallier[] = INCGFX_U32("graphics/pokemon/warrallier/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Warrallier[] = INCGFX_U32("graphics/pokemon/warrallier/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Warrallier[] = INCGFX_U32("graphics/pokemon/warrallier/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Warrallier[] = INCGFX_U32("graphics/pokemon/warrallier/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Warrallier[] = INCGFX_U8("graphics/pokemon/warrallier/icon.png", ".4bpp");
const u8 gMonFootprint_Warrallier[] = INCGFX_U8("graphics/pokemon/warrallier/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Torchbat[] = INCGFX_U32("graphics/pokemon/torchbat/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Torchbat[] = INCGFX_U32("graphics/pokemon/torchbat/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Torchbat[] = INCGFX_U32("graphics/pokemon/torchbat/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Torchbat[] = INCGFX_U32("graphics/pokemon/torchbat/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Torchbat[] = INCGFX_U32("graphics/pokemon/torchbat/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Torchbat[] = INCGFX_U8("graphics/pokemon/torchbat/icon.png", ".4bpp");
const u8 gMonFootprint_Torchbat[] = INCGFX_U8("graphics/pokemon/torchbat/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Heatbat[] = INCGFX_U32("graphics/pokemon/heatbat/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Heatbat[] = INCGFX_U32("graphics/pokemon/heatbat/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Heatbat[] = INCGFX_U32("graphics/pokemon/heatbat/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Heatbat[] = INCGFX_U32("graphics/pokemon/heatbat/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Heatbat[] = INCGFX_U32("graphics/pokemon/heatbat/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Heatbat[] = INCGFX_U8("graphics/pokemon/heatbat/icon.png", ".4bpp");
const u8 gMonFootprint_Heatbat[] = INCGFX_U8("graphics/pokemon/heatbat/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Blazterra[] = INCGFX_U32("graphics/pokemon/blazterra/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Blazterra[] = INCGFX_U32("graphics/pokemon/blazterra/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Blazterra[] = INCGFX_U32("graphics/pokemon/blazterra/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Blazterra[] = INCGFX_U32("graphics/pokemon/blazterra/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Blazterra[] = INCGFX_U32("graphics/pokemon/blazterra/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Blazterra[] = INCGFX_U8("graphics/pokemon/blazterra/icon.png", ".4bpp");
const u8 gMonFootprint_Blazterra[] = INCGFX_U8("graphics/pokemon/blazterra/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Erobi[] = INCGFX_U32("graphics/pokemon/erobi/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Erobi[] = INCGFX_U32("graphics/pokemon/erobi/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Erobi[] = INCGFX_U32("graphics/pokemon/erobi/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Erobi[] = INCGFX_U32("graphics/pokemon/erobi/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Erobi[] = INCGFX_U32("graphics/pokemon/erobi/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Erobi[] = INCGFX_U8("graphics/pokemon/erobi/icon.png", ".4bpp");
const u8 gMonFootprint_Erobi[] = INCGFX_U8("graphics/pokemon/erobi/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Harpie[] = INCGFX_U32("graphics/pokemon/harpie/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Harpie[] = INCGFX_U32("graphics/pokemon/harpie/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Harpie[] = INCGFX_U32("graphics/pokemon/harpie/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Harpie[] = INCGFX_U32("graphics/pokemon/harpie/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Harpie[] = INCGFX_U32("graphics/pokemon/harpie/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Harpie[] = INCGFX_U8("graphics/pokemon/harpie/icon.png", ".4bpp");
const u8 gMonFootprint_Harpie[] = INCGFX_U8("graphics/pokemon/harpie/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Smeatherace[] = INCGFX_U32("graphics/pokemon/smeatherace/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Smeatherace[] = INCGFX_U32("graphics/pokemon/smeatherace/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Smeatherace[] = INCGFX_U32("graphics/pokemon/smeatherace/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Smeatherace[] = INCGFX_U32("graphics/pokemon/smeatherace/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Smeatherace[] = INCGFX_U32("graphics/pokemon/smeatherace/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Smeatherace[] = INCGFX_U8("graphics/pokemon/smeatherace/icon.png", ".4bpp");
const u8 gMonFootprint_Smeatherace[] = INCGFX_U8("graphics/pokemon/smeatherace/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Bolthook[] = INCGFX_U32("graphics/pokemon/bolthook/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Bolthook[] = INCGFX_U32("graphics/pokemon/bolthook/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Bolthook[] = INCGFX_U32("graphics/pokemon/bolthook/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Bolthook[] = INCGFX_U32("graphics/pokemon/bolthook/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Bolthook[] = INCGFX_U32("graphics/pokemon/bolthook/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Bolthook[] = INCGFX_U8("graphics/pokemon/bolthook/icon.png", ".4bpp");
const u8 gMonFootprint_Bolthook[] = INCGFX_U8("graphics/pokemon/bolthook/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Wump[] = INCGFX_U32("graphics/pokemon/wump/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Wump[] = INCGFX_U32("graphics/pokemon/wump/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Wump[] = INCGFX_U32("graphics/pokemon/wump/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Wump[] = INCGFX_U32("graphics/pokemon/wump/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Wump[] = INCGFX_U32("graphics/pokemon/wump/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Wump[] = INCGFX_U8("graphics/pokemon/wump/icon.png", ".4bpp");
const u8 gMonFootprint_Wump[] = INCGFX_U8("graphics/pokemon/wump/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Twemp[] = INCGFX_U32("graphics/pokemon/twemp/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Twemp[] = INCGFX_U32("graphics/pokemon/twemp/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Twemp[] = INCGFX_U32("graphics/pokemon/twemp/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Twemp[] = INCGFX_U32("graphics/pokemon/twemp/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Twemp[] = INCGFX_U32("graphics/pokemon/twemp/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Twemp[] = INCGFX_U8("graphics/pokemon/twemp/icon.png", ".4bpp");
const u8 gMonFootprint_Twemp[] = INCGFX_U8("graphics/pokemon/twemp/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Florantula[] = INCGFX_U32("graphics/pokemon/florantula/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Florantula[] = INCGFX_U32("graphics/pokemon/florantula/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Florantula[] = INCGFX_U32("graphics/pokemon/florantula/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Florantula[] = INCGFX_U32("graphics/pokemon/florantula/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Florantula[] = INCGFX_U32("graphics/pokemon/florantula/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Florantula[] = INCGFX_U8("graphics/pokemon/florantula/icon.png", ".4bpp");
const u8 gMonFootprint_Florantula[] = INCGFX_U8("graphics/pokemon/florantula/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Cowfin[] = INCGFX_U32("graphics/pokemon/cowfin/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Cowfin[] = INCGFX_U32("graphics/pokemon/cowfin/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Cowfin[] = INCGFX_U32("graphics/pokemon/cowfin/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Cowfin[] = INCGFX_U32("graphics/pokemon/cowfin/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Cowfin[] = INCGFX_U32("graphics/pokemon/cowfin/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Cowfin[] = INCGFX_U8("graphics/pokemon/cowfin/icon.png", ".4bpp");
const u8 gMonFootprint_Cowfin[] = INCGFX_U8("graphics/pokemon/cowfin/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Mooceon[] = INCGFX_U32("graphics/pokemon/mooceon/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Mooceon[] = INCGFX_U32("graphics/pokemon/mooceon/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Mooceon[] = INCGFX_U32("graphics/pokemon/mooceon/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Mooceon[] = INCGFX_U32("graphics/pokemon/mooceon/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Mooceon[] = INCGFX_U32("graphics/pokemon/mooceon/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Mooceon[] = INCGFX_U8("graphics/pokemon/mooceon/icon.png", ".4bpp");
const u8 gMonFootprint_Mooceon[] = INCGFX_U8("graphics/pokemon/mooceon/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Lapper[] = INCGFX_U32("graphics/pokemon/lapper/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Lapper[] = INCGFX_U32("graphics/pokemon/lapper/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Lapper[] = INCGFX_U32("graphics/pokemon/lapper/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Lapper[] = INCGFX_U32("graphics/pokemon/lapper/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Lapper[] = INCGFX_U32("graphics/pokemon/lapper/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Lapper[] = INCGFX_U8("graphics/pokemon/lapper/icon.png", ".4bpp");
const u8 gMonFootprint_Lapper[] = INCGFX_U8("graphics/pokemon/lapper/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Brawleo[] = INCGFX_U32("graphics/pokemon/brawleo/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Brawleo[] = INCGFX_U32("graphics/pokemon/brawleo/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Brawleo[] = INCGFX_U32("graphics/pokemon/brawleo/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Brawleo[] = INCGFX_U32("graphics/pokemon/brawleo/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Brawleo[] = INCGFX_U32("graphics/pokemon/brawleo/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Brawleo[] = INCGFX_U8("graphics/pokemon/brawleo/icon.png", ".4bpp");
const u8 gMonFootprint_Brawleo[] = INCGFX_U8("graphics/pokemon/brawleo/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_IcyFreeze[] = INCGFX_U32("graphics/pokemon/icy_freeze/front.png", ".4bpp.lz");
const u32 gMonFrontPic_IcyFreeze[] = INCGFX_U32("graphics/pokemon/icy_freeze/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_IcyFreeze[] = INCGFX_U32("graphics/pokemon/icy_freeze/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_IcyFreeze[] = INCGFX_U32("graphics/pokemon/icy_freeze/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_IcyFreeze[] = INCGFX_U32("graphics/pokemon/icy_freeze/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_IcyFreeze[] = INCGFX_U8("graphics/pokemon/icy_freeze/icon.png", ".4bpp");
const u8 gMonFootprint_IcyFreeze[] = INCGFX_U8("graphics/pokemon/icy_freeze/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Freezrick[] = INCGFX_U32("graphics/pokemon/freezrick/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Freezrick[] = INCGFX_U32("graphics/pokemon/freezrick/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Freezrick[] = INCGFX_U32("graphics/pokemon/freezrick/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Freezrick[] = INCGFX_U32("graphics/pokemon/freezrick/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Freezrick[] = INCGFX_U32("graphics/pokemon/freezrick/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Freezrick[] = INCGFX_U8("graphics/pokemon/freezrick/icon.png", ".4bpp");
const u8 gMonFootprint_Freezrick[] = INCGFX_U8("graphics/pokemon/freezrick/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Bulbtle[] = INCGFX_U32("graphics/pokemon/bulbtle/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Bulbtle[] = INCGFX_U32("graphics/pokemon/bulbtle/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Bulbtle[] = INCGFX_U32("graphics/pokemon/bulbtle/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Bulbtle[] = INCGFX_U32("graphics/pokemon/bulbtle/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Bulbtle[] = INCGFX_U32("graphics/pokemon/bulbtle/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Bulbtle[] = INCGFX_U8("graphics/pokemon/bulbtle/icon.png", ".4bpp");
const u8 gMonFootprint_Bulbtle[] = INCGFX_U8("graphics/pokemon/bulbtle/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Bulbtoise[] = INCGFX_U32("graphics/pokemon/bulbtoise/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Bulbtoise[] = INCGFX_U32("graphics/pokemon/bulbtoise/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Bulbtoise[] = INCGFX_U32("graphics/pokemon/bulbtoise/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Bulbtoise[] = INCGFX_U32("graphics/pokemon/bulbtoise/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Bulbtoise[] = INCGFX_U32("graphics/pokemon/bulbtoise/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Bulbtoise[] = INCGFX_U8("graphics/pokemon/bulbtoise/icon.png", ".4bpp");
const u8 gMonFootprint_Bulbtoise[] = INCGFX_U8("graphics/pokemon/bulbtoise/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Eiscue[] = INCGFX_U32("graphics/pokemon/eiscue/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Eiscue[] = INCGFX_U32("graphics/pokemon/eiscue/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Eiscue[] = INCGFX_U32("graphics/pokemon/eiscue/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Eiscue[] = INCGFX_U32("graphics/pokemon/eiscue/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Eiscue[] = INCGFX_U32("graphics/pokemon/eiscue/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Eiscue[] = INCGFX_U8("graphics/pokemon/eiscue/icon.png", ".4bpp");
const u8 gMonFootprint_Eiscue[] = INCGFX_U8("graphics/pokemon/eiscue/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Rainbro[] = INCGFX_U32("graphics/pokemon/rainbro/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Rainbro[] = INCGFX_U32("graphics/pokemon/rainbro/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Rainbro[] = INCGFX_U32("graphics/pokemon/rainbro/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Rainbro[] = INCGFX_U32("graphics/pokemon/rainbro/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Rainbro[] = INCGFX_U32("graphics/pokemon/rainbro/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Rainbro[] = INCGFX_U8("graphics/pokemon/rainbro/icon.png", ".4bpp");
const u8 gMonFootprint_Rainbro[] = INCGFX_U8("graphics/pokemon/rainbro/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Nukfae[] = INCGFX_U32("graphics/pokemon/nukfae/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Nukfae[] = INCGFX_U32("graphics/pokemon/nukfae/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Nukfae[] = INCGFX_U32("graphics/pokemon/nukfae/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Nukfae[] = INCGFX_U32("graphics/pokemon/nukfae/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Nukfae[] = INCGFX_U32("graphics/pokemon/nukfae/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Nukfae[] = INCGFX_U8("graphics/pokemon/nukfae/icon.png", ".4bpp");
const u8 gMonFootprint_Nukfae[] = INCGFX_U8("graphics/pokemon/nukfae/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Toxiren[] = INCGFX_U32("graphics/pokemon/toxiren/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Toxiren[] = INCGFX_U32("graphics/pokemon/toxiren/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Toxiren[] = INCGFX_U32("graphics/pokemon/toxiren/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Toxiren[] = INCGFX_U32("graphics/pokemon/toxiren/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Toxiren[] = INCGFX_U32("graphics/pokemon/toxiren/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Toxiren[] = INCGFX_U8("graphics/pokemon/toxiren/icon.png", ".4bpp");
const u8 gMonFootprint_Toxiren[] = INCGFX_U8("graphics/pokemon/toxiren/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Stonma[] = INCGFX_U32("graphics/pokemon/stonma/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Stonma[] = INCGFX_U32("graphics/pokemon/stonma/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Stonma[] = INCGFX_U32("graphics/pokemon/stonma/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Stonma[] = INCGFX_U32("graphics/pokemon/stonma/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Stonma[] = INCGFX_U32("graphics/pokemon/stonma/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Stonma[] = INCGFX_U8("graphics/pokemon/stonma/icon.png", ".4bpp");
const u8 gMonFootprint_Stonma[] = INCGFX_U8("graphics/pokemon/stonma/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Sigmauler[] = INCGFX_U32("graphics/pokemon/sigmauler/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Sigmauler[] = INCGFX_U32("graphics/pokemon/sigmauler/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Sigmauler[] = INCGFX_U32("graphics/pokemon/sigmauler/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Sigmauler[] = INCGFX_U32("graphics/pokemon/sigmauler/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Sigmauler[] = INCGFX_U32("graphics/pokemon/sigmauler/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Sigmauler[] = INCGFX_U8("graphics/pokemon/sigmauler/icon.png", ".4bpp");
const u8 gMonFootprint_Sigmauler[] = INCGFX_U8("graphics/pokemon/sigmauler/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Tinky[] = INCGFX_U32("graphics/pokemon/tinky/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Tinky[] = INCGFX_U32("graphics/pokemon/tinky/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Tinky[] = INCGFX_U32("graphics/pokemon/tinky/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Tinky[] = INCGFX_U32("graphics/pokemon/tinky/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Tinky[] = INCGFX_U32("graphics/pokemon/tinky/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Tinky[] = INCGFX_U8("graphics/pokemon/tinky/icon.png", ".4bpp");
const u8 gMonFootprint_Tinky[] = INCGFX_U8("graphics/pokemon/tinky/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Motinky[] = INCGFX_U32("graphics/pokemon/motinky/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Motinky[] = INCGFX_U32("graphics/pokemon/motinky/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Motinky[] = INCGFX_U32("graphics/pokemon/motinky/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Motinky[] = INCGFX_U32("graphics/pokemon/motinky/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Motinky[] = INCGFX_U32("graphics/pokemon/motinky/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Motinky[] = INCGFX_U8("graphics/pokemon/motinky/icon.png", ".4bpp");
const u8 gMonFootprint_Motinky[] = INCGFX_U8("graphics/pokemon/motinky/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Gortiki[] = INCGFX_U32("graphics/pokemon/gortiki/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Gortiki[] = INCGFX_U32("graphics/pokemon/gortiki/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Gortiki[] = INCGFX_U32("graphics/pokemon/gortiki/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Gortiki[] = INCGFX_U32("graphics/pokemon/gortiki/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Gortiki[] = INCGFX_U32("graphics/pokemon/gortiki/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Gortiki[] = INCGFX_U8("graphics/pokemon/gortiki/icon.png", ".4bpp");
const u8 gMonFootprint_Gortiki[] = INCGFX_U8("graphics/pokemon/gortiki/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Chebbi[] = INCGFX_U32("graphics/pokemon/chebbi/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Chebbi[] = INCGFX_U32("graphics/pokemon/chebbi/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Chebbi[] = INCGFX_U32("graphics/pokemon/chebbi/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Chebbi[] = INCGFX_U32("graphics/pokemon/chebbi/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Chebbi[] = INCGFX_U32("graphics/pokemon/chebbi/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Chebbi[] = INCGFX_U8("graphics/pokemon/chebbi/icon.png", ".4bpp");
const u8 gMonFootprint_Chebbi[] = INCGFX_U8("graphics/pokemon/chebbi/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Devampry[] = INCGFX_U32("graphics/pokemon/devampry/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Devampry[] = INCGFX_U32("graphics/pokemon/devampry/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Devampry[] = INCGFX_U32("graphics/pokemon/devampry/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Devampry[] = INCGFX_U32("graphics/pokemon/devampry/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Devampry[] = INCGFX_U32("graphics/pokemon/devampry/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Devampry[] = INCGFX_U8("graphics/pokemon/devampry/icon.png", ".4bpp");
const u8 gMonFootprint_Devampry[] = INCGFX_U8("graphics/pokemon/devampry/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Zapana[] = INCGFX_U32("graphics/pokemon/zapana/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Zapana[] = INCGFX_U32("graphics/pokemon/zapana/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Zapana[] = INCGFX_U32("graphics/pokemon/zapana/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Zapana[] = INCGFX_U32("graphics/pokemon/zapana/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Zapana[] = INCGFX_U32("graphics/pokemon/zapana/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Zapana[] = INCGFX_U8("graphics/pokemon/zapana/icon.png", ".4bpp");
const u8 gMonFootprint_Zapana[] = INCGFX_U8("graphics/pokemon/zapana/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Ampeel[] = INCGFX_U32("graphics/pokemon/ampeel/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Ampeel[] = INCGFX_U32("graphics/pokemon/ampeel/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Ampeel[] = INCGFX_U32("graphics/pokemon/ampeel/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Ampeel[] = INCGFX_U32("graphics/pokemon/ampeel/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Ampeel[] = INCGFX_U32("graphics/pokemon/ampeel/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Ampeel[] = INCGFX_U8("graphics/pokemon/ampeel/icon.png", ".4bpp");
const u8 gMonFootprint_Ampeel[] = INCGFX_U8("graphics/pokemon/ampeel/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Beatld[] = INCGFX_U32("graphics/pokemon/beatld/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Beatld[] = INCGFX_U32("graphics/pokemon/beatld/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Beatld[] = INCGFX_U32("graphics/pokemon/beatld/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Beatld[] = INCGFX_U32("graphics/pokemon/beatld/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Beatld[] = INCGFX_U32("graphics/pokemon/beatld/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Beatld[] = INCGFX_U8("graphics/pokemon/beatld/icon.png", ".4bpp");
const u8 gMonFootprint_Beatld[] = INCGFX_U8("graphics/pokemon/beatld/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Wispole[] = INCGFX_U32("graphics/pokemon/wispole/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Wispole[] = INCGFX_U32("graphics/pokemon/wispole/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Wispole[] = INCGFX_U32("graphics/pokemon/wispole/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Wispole[] = INCGFX_U32("graphics/pokemon/wispole/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Wispole[] = INCGFX_U32("graphics/pokemon/wispole/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Wispole[] = INCGFX_U8("graphics/pokemon/wispole/icon.png", ".4bpp");
const u8 gMonFootprint_Wispole[] = INCGFX_U8("graphics/pokemon/wispole/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Galfrogtom[] = INCGFX_U32("graphics/pokemon/galfrogtom/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Galfrogtom[] = INCGFX_U32("graphics/pokemon/galfrogtom/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Galfrogtom[] = INCGFX_U32("graphics/pokemon/galfrogtom/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Galfrogtom[] = INCGFX_U32("graphics/pokemon/galfrogtom/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Galfrogtom[] = INCGFX_U32("graphics/pokemon/galfrogtom/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Galfrogtom[] = INCGFX_U8("graphics/pokemon/galfrogtom/icon.png", ".4bpp");
const u8 gMonFootprint_Galfrogtom[] = INCGFX_U8("graphics/pokemon/galfrogtom/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_GigaCircuit[] = INCGFX_U32("graphics/pokemon/giga_circuit/front.png", ".4bpp.lz");
const u32 gMonFrontPic_GigaCircuit[] = INCGFX_U32("graphics/pokemon/giga_circuit/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_GigaCircuit[] = INCGFX_U32("graphics/pokemon/giga_circuit/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_GigaCircuit[] = INCGFX_U32("graphics/pokemon/giga_circuit/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_GigaCircuit[] = INCGFX_U32("graphics/pokemon/giga_circuit/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_GigaCircuit[] = INCGFX_U8("graphics/pokemon/giga_circuit/icon.png", ".4bpp");
const u8 gMonFootprint_GigaCircuit[] = INCGFX_U8("graphics/pokemon/giga_circuit/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_BulgarianUnown[] = INCGFX_U32("graphics/pokemon/bulgarian_unown/front.png", ".4bpp.lz");
const u32 gMonFrontPic_BulgarianUnown[] = INCGFX_U32("graphics/pokemon/bulgarian_unown/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_BulgarianUnown[] = INCGFX_U32("graphics/pokemon/bulgarian_unown/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_BulgarianUnown[] = INCGFX_U32("graphics/pokemon/bulgarian_unown/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_BulgarianUnown[] = INCGFX_U32("graphics/pokemon/bulgarian_unown/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_BulgarianUnown[] = INCGFX_U8("graphics/pokemon/bulgarian_unown/icon.png", ".4bpp");
const u8 gMonFootprint_BulgarianUnown[] = INCGFX_U8("graphics/pokemon/bulgarian_unown/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_United[] = INCGFX_U32("graphics/pokemon/united/front.png", ".4bpp.lz");
const u32 gMonFrontPic_United[] = INCGFX_U32("graphics/pokemon/united/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_United[] = INCGFX_U32("graphics/pokemon/united/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_United[] = INCGFX_U32("graphics/pokemon/united/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_United[] = INCGFX_U32("graphics/pokemon/united/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_United[] = INCGFX_U8("graphics/pokemon/united/icon.png", ".4bpp");
const u8 gMonFootprint_United[] = INCGFX_U8("graphics/pokemon/united/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Hairyen[] = INCGFX_U32("graphics/pokemon/hairyen/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Hairyen[] = INCGFX_U32("graphics/pokemon/hairyen/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Hairyen[] = INCGFX_U32("graphics/pokemon/hairyen/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Hairyen[] = INCGFX_U32("graphics/pokemon/hairyen/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Hairyen[] = INCGFX_U32("graphics/pokemon/hairyen/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Hairyen[] = INCGFX_U8("graphics/pokemon/hairyen/icon.png", ".4bpp");
const u8 gMonFootprint_Hairyen[] = INCGFX_U8("graphics/pokemon/hairyen/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Panzerien[] = INCGFX_U32("graphics/pokemon/panzerien/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Panzerien[] = INCGFX_U32("graphics/pokemon/panzerien/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Panzerien[] = INCGFX_U32("graphics/pokemon/panzerien/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Panzerien[] = INCGFX_U32("graphics/pokemon/panzerien/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Panzerien[] = INCGFX_U32("graphics/pokemon/panzerien/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Panzerien[] = INCGFX_U8("graphics/pokemon/panzerien/icon.png", ".4bpp");
const u8 gMonFootprint_Panzerien[] = INCGFX_U8("graphics/pokemon/panzerien/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Nucloid[] = INCGFX_U32("graphics/pokemon/nucloid/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Nucloid[] = INCGFX_U32("graphics/pokemon/nucloid/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Nucloid[] = INCGFX_U32("graphics/pokemon/nucloid/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Nucloid[] = INCGFX_U32("graphics/pokemon/nucloid/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Nucloid[] = INCGFX_U32("graphics/pokemon/nucloid/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Nucloid[] = INCGFX_U8("graphics/pokemon/nucloid/icon.png", ".4bpp");
const u8 gMonFootprint_Nucloid[] = INCGFX_U8("graphics/pokemon/nucloid/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Nuclobyl[] = INCGFX_U32("graphics/pokemon/nuclobyl/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Nuclobyl[] = INCGFX_U32("graphics/pokemon/nuclobyl/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Nuclobyl[] = INCGFX_U32("graphics/pokemon/nuclobyl/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Nuclobyl[] = INCGFX_U32("graphics/pokemon/nuclobyl/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Nuclobyl[] = INCGFX_U32("graphics/pokemon/nuclobyl/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Nuclobyl[] = INCGFX_U8("graphics/pokemon/nuclobyl/icon.png", ".4bpp");
const u8 gMonFootprint_Nuclobyl[] = INCGFX_U8("graphics/pokemon/nuclobyl/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Gentie[] = INCGFX_U32("graphics/pokemon/gentie/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Gentie[] = INCGFX_U32("graphics/pokemon/gentie/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Gentie[] = INCGFX_U32("graphics/pokemon/gentie/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Gentie[] = INCGFX_U32("graphics/pokemon/gentie/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Gentie[] = INCGFX_U32("graphics/pokemon/gentie/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Gentie[] = INCGFX_U8("graphics/pokemon/gentie/icon.png", ".4bpp");
const u8 gMonFootprint_Gentie[] = INCGFX_U8("graphics/pokemon/gentie/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Yanklet[] = INCGFX_U32("graphics/pokemon/yanklet/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Yanklet[] = INCGFX_U32("graphics/pokemon/yanklet/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Yanklet[] = INCGFX_U32("graphics/pokemon/yanklet/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Yanklet[] = INCGFX_U32("graphics/pokemon/yanklet/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Yanklet[] = INCGFX_U32("graphics/pokemon/yanklet/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Yanklet[] = INCGFX_U8("graphics/pokemon/yanklet/icon.png", ".4bpp");
const u8 gMonFootprint_Yanklet[] = INCGFX_U8("graphics/pokemon/yanklet/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Anjane[] = INCGFX_U32("graphics/pokemon/anjane/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Anjane[] = INCGFX_U32("graphics/pokemon/anjane/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Anjane[] = INCGFX_U32("graphics/pokemon/anjane/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Anjane[] = INCGFX_U32("graphics/pokemon/anjane/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Anjane[] = INCGFX_U32("graphics/pokemon/anjane/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Anjane[] = INCGFX_U8("graphics/pokemon/anjane/icon.png", ".4bpp");
const u8 gMonFootprint_Anjane[] = INCGFX_U8("graphics/pokemon/anjane/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Janenon[] = INCGFX_U32("graphics/pokemon/janenon/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Janenon[] = INCGFX_U32("graphics/pokemon/janenon/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Janenon[] = INCGFX_U32("graphics/pokemon/janenon/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Janenon[] = INCGFX_U32("graphics/pokemon/janenon/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Janenon[] = INCGFX_U32("graphics/pokemon/janenon/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Janenon[] = INCGFX_U8("graphics/pokemon/janenon/icon.png", ".4bpp");
const u8 gMonFootprint_Janenon[] = INCGFX_U8("graphics/pokemon/janenon/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Saucerl[] = INCGFX_U32("graphics/pokemon/saucerl/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Saucerl[] = INCGFX_U32("graphics/pokemon/saucerl/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Saucerl[] = INCGFX_U32("graphics/pokemon/saucerl/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Saucerl[] = INCGFX_U32("graphics/pokemon/saucerl/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Saucerl[] = INCGFX_U32("graphics/pokemon/saucerl/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Saucerl[] = INCGFX_U8("graphics/pokemon/saucerl/icon.png", ".4bpp");
const u8 gMonFootprint_Saucerl[] = INCGFX_U8("graphics/pokemon/saucerl/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Abyssys[] = INCGFX_U32("graphics/pokemon/abyssys/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Abyssys[] = INCGFX_U32("graphics/pokemon/abyssys/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Abyssys[] = INCGFX_U32("graphics/pokemon/abyssys/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Abyssys[] = INCGFX_U32("graphics/pokemon/abyssys/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Abyssys[] = INCGFX_U32("graphics/pokemon/abyssys/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Abyssys[] = INCGFX_U8("graphics/pokemon/abyssys/icon.png", ".4bpp");
const u8 gMonFootprint_Abyssys[] = INCGFX_U8("graphics/pokemon/abyssys/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Octopearl[] = INCGFX_U32("graphics/pokemon/octopearl/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Octopearl[] = INCGFX_U32("graphics/pokemon/octopearl/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Octopearl[] = INCGFX_U32("graphics/pokemon/octopearl/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Octopearl[] = INCGFX_U32("graphics/pokemon/octopearl/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Octopearl[] = INCGFX_U32("graphics/pokemon/octopearl/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Octopearl[] = INCGFX_U8("graphics/pokemon/octopearl/icon.png", ".4bpp");
const u8 gMonFootprint_Octopearl[] = INCGFX_U8("graphics/pokemon/octopearl/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Cryoblade[] = INCGFX_U32("graphics/pokemon/cryoblade/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Cryoblade[] = INCGFX_U32("graphics/pokemon/cryoblade/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Cryoblade[] = INCGFX_U32("graphics/pokemon/cryoblade/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Cryoblade[] = INCGFX_U32("graphics/pokemon/cryoblade/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Cryoblade[] = INCGFX_U32("graphics/pokemon/cryoblade/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Cryoblade[] = INCGFX_U8("graphics/pokemon/cryoblade/icon.png", ".4bpp");
const u8 gMonFootprint_Cryoblade[] = INCGFX_U8("graphics/pokemon/cryoblade/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Bygon[] = INCGFX_U32("graphics/pokemon/bygon/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Bygon[] = INCGFX_U32("graphics/pokemon/bygon/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Bygon[] = INCGFX_U32("graphics/pokemon/bygon/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Bygon[] = INCGFX_U32("graphics/pokemon/bygon/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Bygon[] = INCGFX_U32("graphics/pokemon/bygon/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Bygon[] = INCGFX_U8("graphics/pokemon/bygon/icon.png", ".4bpp");
const u8 gMonFootprint_Bygon[] = INCGFX_U8("graphics/pokemon/bygon/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Sandrema[] = INCGFX_U32("graphics/pokemon/sandrema/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Sandrema[] = INCGFX_U32("graphics/pokemon/sandrema/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Sandrema[] = INCGFX_U32("graphics/pokemon/sandrema/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Sandrema[] = INCGFX_U32("graphics/pokemon/sandrema/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Sandrema[] = INCGFX_U32("graphics/pokemon/sandrema/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Sandrema[] = INCGFX_U8("graphics/pokemon/sandrema/icon.png", ".4bpp");
const u8 gMonFootprint_Sandrema[] = INCGFX_U8("graphics/pokemon/sandrema/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Ciggiti[] = INCGFX_U32("graphics/pokemon/ciggiti/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Ciggiti[] = INCGFX_U32("graphics/pokemon/ciggiti/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Ciggiti[] = INCGFX_U32("graphics/pokemon/ciggiti/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Ciggiti[] = INCGFX_U32("graphics/pokemon/ciggiti/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Ciggiti[] = INCGFX_U32("graphics/pokemon/ciggiti/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Ciggiti[] = INCGFX_U8("graphics/pokemon/ciggiti/icon.png", ".4bpp");
const u8 gMonFootprint_Ciggiti[] = INCGFX_U8("graphics/pokemon/ciggiti/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Chuchar[] = INCGFX_U32("graphics/pokemon/chuchar/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Chuchar[] = INCGFX_U32("graphics/pokemon/chuchar/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Chuchar[] = INCGFX_U32("graphics/pokemon/chuchar/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Chuchar[] = INCGFX_U32("graphics/pokemon/chuchar/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Chuchar[] = INCGFX_U32("graphics/pokemon/chuchar/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Chuchar[] = INCGFX_U8("graphics/pokemon/chuchar/icon.png", ".4bpp");
const u8 gMonFootprint_Chuchar[] = INCGFX_U8("graphics/pokemon/chuchar/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Parahaunt[] = INCGFX_U32("graphics/pokemon/parahaunt/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Parahaunt[] = INCGFX_U32("graphics/pokemon/parahaunt/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Parahaunt[] = INCGFX_U32("graphics/pokemon/parahaunt/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Parahaunt[] = INCGFX_U32("graphics/pokemon/parahaunt/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Parahaunt[] = INCGFX_U32("graphics/pokemon/parahaunt/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Parahaunt[] = INCGFX_U8("graphics/pokemon/parahaunt/icon.png", ".4bpp");
const u8 gMonFootprint_Parahaunt[] = INCGFX_U8("graphics/pokemon/parahaunt/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Insectoid[] = INCGFX_U32("graphics/pokemon/insectoid/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Insectoid[] = INCGFX_U32("graphics/pokemon/insectoid/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Insectoid[] = INCGFX_U32("graphics/pokemon/insectoid/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Insectoid[] = INCGFX_U32("graphics/pokemon/insectoid/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Insectoid[] = INCGFX_U32("graphics/pokemon/insectoid/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Insectoid[] = INCGFX_U8("graphics/pokemon/insectoid/icon.png", ".4bpp");
const u8 gMonFootprint_Insectoid[] = INCGFX_U8("graphics/pokemon/insectoid/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Darkgonark[] = INCGFX_U32("graphics/pokemon/darkgonark/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Darkgonark[] = INCGFX_U32("graphics/pokemon/darkgonark/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Darkgonark[] = INCGFX_U32("graphics/pokemon/darkgonark/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Darkgonark[] = INCGFX_U32("graphics/pokemon/darkgonark/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Darkgonark[] = INCGFX_U32("graphics/pokemon/darkgonark/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Darkgonark[] = INCGFX_U8("graphics/pokemon/darkgonark/icon.png", ".4bpp");
const u8 gMonFootprint_Darkgonark[] = INCGFX_U8("graphics/pokemon/darkgonark/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Gravriel[] = INCGFX_U32("graphics/pokemon/gravriel/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Gravriel[] = INCGFX_U32("graphics/pokemon/gravriel/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Gravriel[] = INCGFX_U32("graphics/pokemon/gravriel/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Gravriel[] = INCGFX_U32("graphics/pokemon/gravriel/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Gravriel[] = INCGFX_U32("graphics/pokemon/gravriel/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Gravriel[] = INCGFX_U8("graphics/pokemon/gravriel/icon.png", ".4bpp");
const u8 gMonFootprint_Gravriel[] = INCGFX_U8("graphics/pokemon/gravriel/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Dragem[] = INCGFX_U32("graphics/pokemon/dragem/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Dragem[] = INCGFX_U32("graphics/pokemon/dragem/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Dragem[] = INCGFX_U32("graphics/pokemon/dragem/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Dragem[] = INCGFX_U32("graphics/pokemon/dragem/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Dragem[] = INCGFX_U32("graphics/pokemon/dragem/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Dragem[] = INCGFX_U8("graphics/pokemon/dragem/icon.png", ".4bpp");
const u8 gMonFootprint_Dragem[] = INCGFX_U8("graphics/pokemon/dragem/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Skiirtle[] = INCGFX_U32("graphics/pokemon/skiirtle/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Skiirtle[] = INCGFX_U32("graphics/pokemon/skiirtle/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Skiirtle[] = INCGFX_U32("graphics/pokemon/skiirtle/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Skiirtle[] = INCGFX_U32("graphics/pokemon/skiirtle/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Skiirtle[] = INCGFX_U32("graphics/pokemon/skiirtle/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Skiirtle[] = INCGFX_U8("graphics/pokemon/skiirtle/icon.png", ".4bpp");
const u8 gMonFootprint_Skiirtle[] = INCGFX_U8("graphics/pokemon/skiirtle/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_McSkiirtle[] = INCGFX_U32("graphics/pokemon/mcskiirtle/front.png", ".4bpp.lz");
const u32 gMonFrontPic_McSkiirtle[] = INCGFX_U32("graphics/pokemon/mcskiirtle/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_McSkiirtle[] = INCGFX_U32("graphics/pokemon/mcskiirtle/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_McSkiirtle[] = INCGFX_U32("graphics/pokemon/mcskiirtle/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_McSkiirtle[] = INCGFX_U32("graphics/pokemon/mcskiirtle/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_McSkiirtle[] = INCGFX_U8("graphics/pokemon/mcskiirtle/icon.png", ".4bpp");
const u8 gMonFootprint_McSkiirtle[] = INCGFX_U8("graphics/pokemon/mcskiirtle/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Balleisk[] = INCGFX_U32("graphics/pokemon/balleisk/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Balleisk[] = INCGFX_U32("graphics/pokemon/balleisk/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Balleisk[] = INCGFX_U32("graphics/pokemon/balleisk/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Balleisk[] = INCGFX_U32("graphics/pokemon/balleisk/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Balleisk[] = INCGFX_U32("graphics/pokemon/balleisk/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Balleisk[] = INCGFX_U8("graphics/pokemon/balleisk/icon.png", ".4bpp");
const u8 gMonFootprint_Balleisk[] = INCGFX_U8("graphics/pokemon/balleisk/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Greation[] = INCGFX_U32("graphics/pokemon/greation/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Greation[] = INCGFX_U32("graphics/pokemon/greation/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Greation[] = INCGFX_U32("graphics/pokemon/greation/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Greation[] = INCGFX_U32("graphics/pokemon/greation/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Greation[] = INCGFX_U32("graphics/pokemon/greation/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Greation[] = INCGFX_U8("graphics/pokemon/greation/icon.png", ".4bpp");
const u8 gMonFootprint_Greation[] = INCGFX_U8("graphics/pokemon/greation/footprint.png", ".1bpp");

const u32 gMonStillFrontPic_Ultragon[] = INCGFX_U32("graphics/pokemon/ultragon/front.png", ".4bpp.lz");
const u32 gMonFrontPic_Ultragon[] = INCGFX_U32("graphics/pokemon/ultragon/anim_front.png", ".4bpp.lz");
const u32 gMonPalette_Ultragon[] = INCGFX_U32("graphics/pokemon/ultragon/normal.pal", ".gbapal.lz");
const u32 gMonBackPic_Ultragon[] = INCGFX_U32("graphics/pokemon/ultragon/back.png", ".4bpp.lz");
const u32 gMonShinyPalette_Ultragon[] = INCGFX_U32("graphics/pokemon/ultragon/shiny.pal", ".gbapal.lz");
const u8 gMonIcon_Ultragon[] = INCGFX_U8("graphics/pokemon/ultragon/icon.png", ".4bpp");
const u8 gMonFootprint_Ultragon[] = INCGFX_U8("graphics/pokemon/ultragon/footprint.png", ".1bpp");

