// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/pokemon/level_up_learnsets.h

static const u16 sLeafingLevelUpLearnset[] = {
    LEVEL_UP_MOVE( 1, MOVE_TACKLE),
    LEVEL_UP_MOVE( 1, MOVE_LEER),
    LEVEL_UP_MOVE( 6, MOVE_ABSORB),
    LEVEL_UP_MOVE(10, MOVE_FURY_CUTTER),
    LEVEL_UP_MOVE(15, MOVE_RAZOR_LEAF),
    LEVEL_UP_MOVE(20, MOVE_METAL_CLAW),
    LEVEL_UP_MOVE(25, MOVE_MEGA_DRAIN),
    LEVEL_UP_MOVE(30, MOVE_SLASH),
    LEVEL_UP_MOVE(35, MOVE_IRON_DEFENSE),
    LEVEL_UP_MOVE(40, MOVE_LEAF_BLADE),
    LEVEL_UP_MOVE(45, MOVE_SWORDS_DANCE),
    LEVEL_UP_END
};

static const u16 sLeafsteelLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sLeafaxerLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sWaffyLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sWealtherLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sWarrallierLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sTorchbatLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sHeatbatLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBlazterraLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sErobiLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sHarpieLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sSmeatheraceLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBolthookLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sWumpLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sTwempLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sFlorantulaLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sCowfinLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sMooceonLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sLapperLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBrawleoLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sIcyFreezeLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sFreezrickLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBulbtleLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBulbtoiseLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sEiscueLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sRainbroLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sNukfaeLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sToxirenLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sStonmaLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sSigmaulerLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sTinkyLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sMotinkyLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGortikiLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sChebbiLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sDevampryLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sZapanaLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sAmpeelLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBeatldLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sWispoleLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGalfrogtomLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGigaCircuitLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBulgarianUnownLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sUnitedLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sHairyenLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sPanzerienLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sNucloidLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sNuclobylLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGentieLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sYankletLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sAnjaneLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sJanenonLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sSaucerlLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sAbyssysLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sOctopearlLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sCryobladeLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBygonLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sSandremaLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sCiggitiLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sChucharLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sParahauntLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sInsectoidLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sDarkgonarkLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGravrielLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sDragemLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sSkiirtleLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sMcSkiirtleLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sBalleiskLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sGreationLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

static const u16 sUltragonLevelUpLearnset[] = {
    /* TODO: level-up moves */
    LEVEL_UP_END
};

