// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/pokemon/pokedex_text.h

const u8 gLeafingPokedexText[] = _(
    "LEAFING hides among fallen leaves to\n"
    "nap in the sun. The leaf on its head\n"
    "hardens a little each time it battles,\n"
    "until the edge shines like metal.");

const u8 gLeafsteelPokedexText[] = _(
    "TODO: description");

const u8 gLeafaxerPokedexText[] = _(
    "TODO: description");

const u8 gWaffyPokedexText[] = _(
    "TODO: description");

const u8 gWealtherPokedexText[] = _(
    "TODO: description");

const u8 gWarrallierPokedexText[] = _(
    "TODO: description");

const u8 gTorchbatPokedexText[] = _(
    "TODO: description");

const u8 gHeatbatPokedexText[] = _(
    "TODO: description");

const u8 gBlazterraPokedexText[] = _(
    "TODO: description");

const u8 gErobiPokedexText[] = _(
    "TODO: description");

const u8 gHarpiePokedexText[] = _(
    "TODO: description");

const u8 gSmeatheracePokedexText[] = _(
    "TODO: description");

const u8 gBolthookPokedexText[] = _(
    "TODO: description");

const u8 gWumpPokedexText[] = _(
    "TODO: description");

const u8 gTwempPokedexText[] = _(
    "TODO: description");

const u8 gFlorantulaPokedexText[] = _(
    "TODO: description");

const u8 gCowfinPokedexText[] = _(
    "TODO: description");

const u8 gMooceonPokedexText[] = _(
    "TODO: description");

const u8 gLapperPokedexText[] = _(
    "TODO: description");

const u8 gBrawleoPokedexText[] = _(
    "TODO: description");

const u8 gIcyFreezePokedexText[] = _(
    "TODO: description");

const u8 gFreezrickPokedexText[] = _(
    "TODO: description");

const u8 gBulbtlePokedexText[] = _(
    "TODO: description");

const u8 gBulbtoisePokedexText[] = _(
    "TODO: description");

const u8 gEiscuePokedexText[] = _(
    "TODO: description");

const u8 gRainbroPokedexText[] = _(
    "TODO: description");

const u8 gNukfaePokedexText[] = _(
    "TODO: description");

const u8 gToxirenPokedexText[] = _(
    "TODO: description");

const u8 gStonmaPokedexText[] = _(
    "TODO: description");

const u8 gSigmaulerPokedexText[] = _(
    "TODO: description");

const u8 gTinkyPokedexText[] = _(
    "TODO: description");

const u8 gMotinkyPokedexText[] = _(
    "TODO: description");

const u8 gGortikiPokedexText[] = _(
    "TODO: description");

const u8 gChebbiPokedexText[] = _(
    "TODO: description");

const u8 gDevampryPokedexText[] = _(
    "TODO: description");

const u8 gZapanaPokedexText[] = _(
    "TODO: description");

const u8 gAmpeelPokedexText[] = _(
    "TODO: description");

const u8 gBeatldPokedexText[] = _(
    "TODO: description");

const u8 gWispolePokedexText[] = _(
    "TODO: description");

const u8 gGalfrogtomPokedexText[] = _(
    "TODO: description");

const u8 gGigaCircuitPokedexText[] = _(
    "TODO: description");

const u8 gBulgarianUnownPokedexText[] = _(
    "TODO: description");

const u8 gUnitedPokedexText[] = _(
    "TODO: description");

const u8 gHairyenPokedexText[] = _(
    "TODO: description");

const u8 gPanzerienPokedexText[] = _(
    "TODO: description");

const u8 gNucloidPokedexText[] = _(
    "TODO: description");

const u8 gNuclobylPokedexText[] = _(
    "TODO: description");

const u8 gGentiePokedexText[] = _(
    "TODO: description");

const u8 gYankletPokedexText[] = _(
    "TODO: description");

const u8 gAnjanePokedexText[] = _(
    "TODO: description");

const u8 gJanenonPokedexText[] = _(
    "TODO: description");

const u8 gSaucerlPokedexText[] = _(
    "TODO: description");

const u8 gAbyssysPokedexText[] = _(
    "TODO: description");

const u8 gOctopearlPokedexText[] = _(
    "TODO: description");

const u8 gCryobladePokedexText[] = _(
    "TODO: description");

const u8 gBygonPokedexText[] = _(
    "TODO: description");

const u8 gSandremaPokedexText[] = _(
    "TODO: description");

const u8 gCiggitiPokedexText[] = _(
    "TODO: description");

const u8 gChucharPokedexText[] = _(
    "TODO: description");

const u8 gParahauntPokedexText[] = _(
    "TODO: description");

const u8 gInsectoidPokedexText[] = _(
    "TODO: description");

const u8 gDarkgonarkPokedexText[] = _(
    "TODO: description");

const u8 gGravrielPokedexText[] = _(
    "TODO: description");

const u8 gDragemPokedexText[] = _(
    "TODO: description");

const u8 gSkiirtlePokedexText[] = _(
    "TODO: description");

const u8 gMcSkiirtlePokedexText[] = _(
    "TODO: description");

const u8 gBalleiskPokedexText[] = _(
    "TODO: description");

const u8 gGreationPokedexText[] = _(
    "TODO: description");

const u8 gUltragonPokedexText[] = _(
    "TODO: description");

