// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/pokemon/pokedex_entries.h

    [NATIONAL_DEX_LEAFING] =
    {
        .categoryName = _("SPROUT"),
        .height = 5,
        .weight = 58,
        .description = gLeafingPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_LEAFSTEEL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gLeafsteelPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_LEAFAXER] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gLeafaxerPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_WAFFY] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gWaffyPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_WEALTHER] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gWealtherPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_WARRALLIER] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gWarrallierPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_TORCHBAT] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gTorchbatPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_HEATBAT] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gHeatbatPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BLAZTERRA] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBlazterraPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_EROBI] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gErobiPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_HARPIE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gHarpiePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_SMEATHERACE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gSmeatheracePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BOLTHOOK] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBolthookPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_WUMP] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gWumpPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_TWEMP] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gTwempPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_FLORANTULA] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gFlorantulaPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_COWFIN] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gCowfinPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_MOOCEON] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gMooceonPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_LAPPER] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gLapperPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BRAWLEO] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBrawleoPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_ICY_FREEZE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gIcyFreezePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_FREEZRICK] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gFreezrickPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BULBTLE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBulbtlePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BULBTOISE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBulbtoisePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_EISCUE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gEiscuePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_RAINBRO] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gRainbroPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_NUKFAE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gNukfaePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_TOXIREN] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gToxirenPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_STONMA] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gStonmaPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_SIGMAULER] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gSigmaulerPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_TINKY] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gTinkyPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_MOTINKY] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gMotinkyPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GORTIKI] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGortikiPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_CHEBBI] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gChebbiPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_DEVAMPRY] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gDevampryPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_ZAPANA] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gZapanaPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_AMPEEL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gAmpeelPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BEATLD] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBeatldPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_WISPOLE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gWispolePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GALFROGTOM] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGalfrogtomPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GIGA_CIRCUIT] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGigaCircuitPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BULGARIAN_UNOWN] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBulgarianUnownPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_UNITED] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gUnitedPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_HAIRYEN] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gHairyenPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_PANZERIEN] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gPanzerienPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_NUCLOID] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gNucloidPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_NUCLOBYL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gNuclobylPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GENTIE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGentiePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_YANKLET] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gYankletPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_ANJANE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gAnjanePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_JANENON] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gJanenonPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_SAUCERL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gSaucerlPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_ABYSSYS] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gAbyssysPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_OCTOPEARL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gOctopearlPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_CRYOBLADE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gCryobladePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BYGON] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBygonPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_SANDREMA] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gSandremaPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_CIGGITI] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gCiggitiPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_CHUCHAR] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gChucharPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_PARAHAUNT] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gParahauntPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_INSECTOID] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gInsectoidPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_DARKGONARK] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gDarkgonarkPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GRAVRIEL] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGravrielPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_DRAGEM] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gDragemPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_SKIIRTLE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gSkiirtlePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_MCSKIIRTLE] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gMcSkiirtlePokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_BALLEISK] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gBalleiskPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_GREATION] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gGreationPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

    [NATIONAL_DEX_ULTRAGON] =
    {
        .categoryName = _("TODO"),
        .height = 0 /* TODO: height_m */,
        .weight = 0 /* TODO: weight_kg */,
        .description = gUltragonPokedexText,
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 256,
        .trainerOffset = 0,
    },

