// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.
// Goes into: src/data/pokemon/tmhm_learnsets.h

    [SPECIES_LEAFING] = { .learnset = {
        .TOXIC = TRUE,
        .BULLET_SEED = TRUE,
        .HIDDEN_POWER = TRUE,
        .SUNNY_DAY = TRUE,
        .PROTECT = TRUE,
        .GIGA_DRAIN = TRUE,
        .FRUSTRATION = TRUE,
        .SOLAR_BEAM = TRUE,
        .IRON_TAIL = TRUE,
        .RETURN = TRUE,
        .DOUBLE_TEAM = TRUE,
        .AERIAL_ACE = TRUE,
        .FACADE = TRUE,
        .SECRET_POWER = TRUE,
        .REST = TRUE,
        .ATTRACT = TRUE,
        .CUT = TRUE,
        .STRENGTH = TRUE,
        .FLASH = TRUE,
        .ROCK_SMASH = TRUE,
    } },

    [SPECIES_LEAFSTEEL] = { .learnset = {
    } },

    [SPECIES_LEAFAXER] = { .learnset = {
    } },

    [SPECIES_WAFFY] = { .learnset = {
    } },

    [SPECIES_WEALTHER] = { .learnset = {
    } },

    [SPECIES_WARRALLIER] = { .learnset = {
    } },

    [SPECIES_TORCHBAT] = { .learnset = {
    } },

    [SPECIES_HEATBAT] = { .learnset = {
    } },

    [SPECIES_BLAZTERRA] = { .learnset = {
    } },

    [SPECIES_EROBI] = { .learnset = {
    } },

    [SPECIES_HARPIE] = { .learnset = {
    } },

    [SPECIES_SMEATHERACE] = { .learnset = {
    } },

    [SPECIES_BOLTHOOK] = { .learnset = {
    } },

    [SPECIES_WUMP] = { .learnset = {
    } },

    [SPECIES_TWEMP] = { .learnset = {
    } },

    [SPECIES_FLORANTULA] = { .learnset = {
    } },

    [SPECIES_COWFIN] = { .learnset = {
    } },

    [SPECIES_MOOCEON] = { .learnset = {
    } },

    [SPECIES_LAPPER] = { .learnset = {
    } },

    [SPECIES_BRAWLEO] = { .learnset = {
    } },

    [SPECIES_ICY_FREEZE] = { .learnset = {
    } },

    [SPECIES_FREEZRICK] = { .learnset = {
    } },

    [SPECIES_BULBTLE] = { .learnset = {
    } },

    [SPECIES_BULBTOISE] = { .learnset = {
    } },

    [SPECIES_EISCUE] = { .learnset = {
    } },

    [SPECIES_RAINBRO] = { .learnset = {
    } },

    [SPECIES_NUKFAE] = { .learnset = {
    } },

    [SPECIES_TOXIREN] = { .learnset = {
    } },

    [SPECIES_STONMA] = { .learnset = {
    } },

    [SPECIES_SIGMAULER] = { .learnset = {
    } },

    [SPECIES_TINKY] = { .learnset = {
    } },

    [SPECIES_MOTINKY] = { .learnset = {
    } },

    [SPECIES_GORTIKI] = { .learnset = {
    } },

    [SPECIES_CHEBBI] = { .learnset = {
    } },

    [SPECIES_DEVAMPRY] = { .learnset = {
    } },

    [SPECIES_ZAPANA] = { .learnset = {
    } },

    [SPECIES_AMPEEL] = { .learnset = {
    } },

    [SPECIES_BEATLD] = { .learnset = {
    } },

    [SPECIES_WISPOLE] = { .learnset = {
    } },

    [SPECIES_GALFROGTOM] = { .learnset = {
    } },

    [SPECIES_GIGA_CIRCUIT] = { .learnset = {
    } },

    [SPECIES_BULGARIAN_UNOWN] = { .learnset = {
    } },

    [SPECIES_UNITED] = { .learnset = {
    } },

    [SPECIES_HAIRYEN] = { .learnset = {
    } },

    [SPECIES_PANZERIEN] = { .learnset = {
    } },

    [SPECIES_NUCLOID] = { .learnset = {
    } },

    [SPECIES_NUCLOBYL] = { .learnset = {
    } },

    [SPECIES_GENTIE] = { .learnset = {
    } },

    [SPECIES_YANKLET] = { .learnset = {
    } },

    [SPECIES_ANJANE] = { .learnset = {
    } },

    [SPECIES_JANENON] = { .learnset = {
    } },

    [SPECIES_SAUCERL] = { .learnset = {
    } },

    [SPECIES_ABYSSYS] = { .learnset = {
    } },

    [SPECIES_OCTOPEARL] = { .learnset = {
    } },

    [SPECIES_CRYOBLADE] = { .learnset = {
    } },

    [SPECIES_BYGON] = { .learnset = {
    } },

    [SPECIES_SANDREMA] = { .learnset = {
    } },

    [SPECIES_CIGGITI] = { .learnset = {
    } },

    [SPECIES_CHUCHAR] = { .learnset = {
    } },

    [SPECIES_PARAHAUNT] = { .learnset = {
    } },

    [SPECIES_INSECTOID] = { .learnset = {
    } },

    [SPECIES_DARKGONARK] = { .learnset = {
    } },

    [SPECIES_GRAVRIEL] = { .learnset = {
    } },

    [SPECIES_DRAGEM] = { .learnset = {
    } },

    [SPECIES_SKIIRTLE] = { .learnset = {
    } },

    [SPECIES_MCSKIIRTLE] = { .learnset = {
    } },

    [SPECIES_BALLEISK] = { .learnset = {
    } },

    [SPECIES_GREATION] = { .learnset = {
    } },

    [SPECIES_ULTRAGON] = { .learnset = {
    } },

