"""Our sprite as GBA data for the 96x96 prototype: a 96x96 (or 64x64) 4bpp picture cut into the blocks
the subsprites show (64x64, 32x64, 64x32, 32x32), each block's tiles in row order, plus its palette."""
import sys
import numpy as np
from PIL import Image

src, frame, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
im = Image.open(src).convert("RGBA")
canvas = Image.new("RGBA", (frame, frame), (0, 0, 0, 0))
canvas.alpha_composite(im, ((frame - im.width) // 2, frame - im.height))     # bottom centred, as the games do
a = np.array(canvas)
colours = []
idx = np.zeros((frame, frame), np.uint8)
for y in range(frame):
    for x in range(frame):
        if a[y, x, 3] < 128:
            continue
        c = tuple(int(v) >> 3 for v in a[y, x, :3])
        if c not in colours:
            colours.append(c)
        idx[y, x] = colours.index(c) + 1
assert len(colours) <= 15, len(colours)
blocks = [(0, 0, 64, 64), (64, 0, 32, 64), (0, 64, 64, 32), (64, 64, 32, 32)] if frame == 96 else [(0, 0, 64, 64)]
data = bytearray()
for bx, by, bw, bh in blocks:
    for ty in range(bh // 8):
        for tx in range(bw // 8):
            for row in range(8):
                for col in range(0, 8, 2):
                    y, x = by + ty * 8 + row, bx + tx * 8 + col
                    data.append(idx[y, x] | (idx[y, x + 1] << 4))
pal = [0] + [r | (g << 5) | (b << 10) for r, g, b in colours] + [0] * (15 - len(colours))
with open(out, "w") as f:
    f.write("// Generated by make_bigpic.py from our sprite (no Nintendo data)\n")
    f.write("static const u16 sBigPicPal[16] = {%s};\n" % ", ".join("0x%04X" % p for p in pal))
    f.write("#define BIG_PIC_FRAME %d\n" % frame)
    f.write("static const u32 sBigPicGfx[%d] = {\n" % (len(data) // 4))
    words = np.frombuffer(bytes(data), "<u4")
    for i in range(0, len(words), 8):
        f.write("    " + ", ".join("0x%08X" % w for w in words[i:i + 8]) + ",\n")
    f.write("};\n")
print(out, len(data), "bytes", len(colours), "colours")
