#!/usr/bin/env python3
"""Generate DEX.md, TODO.md and everything in export/ from data/species/.

These files are generated - never edit them by hand, edit the species files instead.
"""
import csv
import json

import dexlib
import build_site
import export_expansion
from dexlib import ROOT, STATS, section, listing

GENERATED = "<!-- GENERATED by scripts/build.py - do not edit by hand, edit data/species/*.yaml instead -->\n\n"


# Column in dex.csv -> (header in the Google Sheet, hint shown in the row below the header).
SHEET_COLUMNS = {
    "dex": ("Dex #", ""),
    "name": ("Name", "max 12 letters (never change the Dex # column)"),
    "type_1": ("Type 1", "Grass, Fire, Water ..."),
    "type_2": ("Type 2", "empty if only one"),
    "ability_1": ("Ability 1", "existing or new"),
    "ability_2": ("Ability 2", "optional"),
    "hidden_ability": ("Hidden ability", "optional"),
    "bst": ("BST", "calculated"),
    "hp": ("HP", "1-255"),
    "attack": ("Attack", "1-255"),
    "defense": ("Defense", "1-255"),
    "sp_attack": ("Sp. Attack", "1-255"),
    "sp_defense": ("Sp. Defense", "1-255"),
    "speed": ("Speed", "1-255"),
    "evolves_from": ("Evolves from", "name of the earlier Pokemon"),
    "evo_condition": ("Evo condition", "Lv 16 / Thunder Stone / Trade / Friendship / Other: ..."),
    "category": ("Category", "e.g. Seed - max 12 letters"),
    "height_m": ("Height (m)", "e.g. 0.7"),
    "weight_kg": ("Weight (kg)", "e.g. 6.9"),
    "body_color": ("Body color", "red blue yellow green black brown purple gray white pink"),
    "ev_yield": ("EV yield", "1 attack, 1 speed (max 3 in total)"),
    "catch_rate": ("Catch rate", "3 hard - 255 easy"),
    "base_exp": ("Base exp", "e.g. 64"),
    "growth_rate": ("Growth rate", "erratic fast medium_fast medium_slow slow fluctuating"),
    "base_friendship": ("Base friendship", "70 is normal"),
    "gender": ("Gender (% male)", "87.5 / 50 / 0 / 100 / genderless"),
    "egg_group_1": ("Egg group 1", "monster water_1 water_2 water_3 bug flying field fairy grass human_like mineral amorphous dragon ditto undiscovered"),
    "egg_group_2": ("Egg group 2", "optional"),
    "egg_cycles": ("Egg cycles", "20 is normal"),
    "held_item_common": ("Held item (common)", "optional"),
    "held_item_rare": ("Held item (rare)", "optional"),
    "level_up_moves": ("Level-up moves", "Tackle (1), Leer (4), Absorb (7). Learned when evolving: Slash (evo)"),
    "tm_hm_moves": ("TM/HM moves", "Cut, Toxic, Protect"),
    "tutor_moves": ("Tutor moves", "Body Slam, Snore"),
    "egg_moves": ("Egg moves", "Leech Seed, Synthesis"),
    "encounters": ("Encounters", "Route 1 | grass | 2-4 | 20; Sigma Cave | cave | 8-10 | 5"),
    "description": ("Pokedex entry", "max 4 short lines"),
    "concept": ("Concept", "what is it?"),
    "name_origin": ("Name origin", "where the name comes from"),
    "notes": ("Notes", "anything else"),
    "designer": ("Designer", "Discord name"),
    "artist": ("Artist", "Discord name"),
}


def evolution_text(evo, names):
    return names.get(evo.get("into"), evo.get("into")), dexlib.evolution_to_text(evo)


def main():
    config = dexlib.load_config()
    dex_size = config.get("dex_size", 151)
    species, problems = dexlib.load_species()
    if problems:
        for path, msg in problems:
            print("ERROR %s: %s" % (path.relative_to(ROOT), msg))
        raise SystemExit("Fix the files above first (run scripts/validate.py).")

    by_dex = {data.get("dex"): (sid, data) for sid, _, data in species}
    names = {sid: data.get("name") for sid, _, data in species}
    evolves_from = {}
    for sid, _, data in species:
        for evo in listing(data.get("evolutions")):
            if isinstance(evo, dict):
                evolves_from[evo.get("into")] = (data.get("name"), evolution_text(evo, names)[1])

    # ---- DEX.md ----
    done = sum(1 for _, _, d in species if dexlib.completeness(d) == 100)
    average = round(sum(dexlib.completeness(d) for _, _, d in species) / len(species)) if species else 0
    lines = [GENERATED, "# %s\n" % config.get("project", "Pokedex"),
             "**%d / %d** slots have a Pokemon - **%d** are fully complete - average completeness **%d%%**.\n"
             % (len(species), dex_size, done, average),
             "What is still missing for each one: [TODO.md](TODO.md)\n",
             "| # | Name | Types | Abilities | BST | Evolves into | Done |",
             "|--:|------|-------|-----------|----:|--------------|-----:|"]
    for dex in range(1, dex_size + 1):
        if dex not in by_dex:
            lines.append("| %d | *open slot* | | | | | |" % dex)
            continue
        sid, data = by_dex[dex]
        abilities = section(data, "abilities")
        ability_names = [str(abilities[k]) + (" (H)" if k == "hidden" else "")
                         for k in ("primary", "secondary", "hidden") if abilities.get(k)]
        evos = ["%s (%s)" % evolution_text(e, names) for e in listing(data.get("evolutions")) if isinstance(e, dict)]
        total = dexlib.bst(data)
        lines.append("| %d | [%s](data/species/%s.yaml) | %s | %s | %s | %s | %d%% |" % (
            dex, data.get("name"), sid, " / ".join(str(t) for t in listing(data.get("types"))),
            ", ".join(ability_names), total if total is not None else "", ", ".join(evos),
            dexlib.completeness(data)))
    (ROOT / "DEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- TODO.md ----
    lines = [GENERATED, "# What is left to do\n",
             "A Pokemon is complete when every item below is filled in. Field guide: [docs/FIELDS.md](docs/FIELDS.md)\n",
             "## Progress per area\n", "| Area | Item | Filled in |", "|------|------|----------:|"]
    for sec, label, test in dexlib.CHECKS:
        count = sum(1 for _, _, d in species if test(d))
        lines.append("| %s | %s | %d / %d |" % (sec, label, count, len(species)))
    open_slots = [str(d) for d in range(1, dex_size + 1) if d not in by_dex]
    lines += ["", "## Open dex slots (%d)\n" % len(open_slots), ", ".join("#" + s for s in open_slots) or "None", "",
              "## Missing per Pokemon\n"]
    for sid, _, data in species:
        gaps = dexlib.missing(data)
        if not gaps:
            continue
        lines.append("### #%s [%s](data/species/%s.yaml) - %d%%\n" % (data.get("dex"), data.get("name"), sid, dexlib.completeness(data)))
        for sec in dexlib.SECTIONS:
            labels = [label for s, label in gaps if s == sec]
            if labels:
                lines.append("- **%s:** %s" % (sec, ", ".join(labels)))
        lines.append("")
    (ROOT / "TODO.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- export/dex.csv (one row per slot, opens in Google Sheets / Excel) ----
    export = ROOT / "export"
    export.mkdir(exist_ok=True)
    header = ["dex", "id", "name", "type_1", "type_2", "ability_1", "ability_2", "hidden_ability", "bst"] + STATS + [
        "evolves_from", "evo_condition", "category", "height_m", "weight_kg", "body_color", "ev_yield", "catch_rate",
        "base_exp", "growth_rate", "base_friendship", "gender", "egg_group_1", "egg_group_2", "egg_cycles",
        "held_item_common", "held_item_rare", "level_up_moves", "tm_hm_moves", "tutor_moves", "egg_moves",
        "encounters", "description", "concept", "name_origin", "notes", "designer", "artist", "complete_percent"]
    with open(export / "dex.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        for dex in range(1, dex_size + 1):
            if dex not in by_dex:
                writer.writerow([dex] + [""] * (len(header) - 1))
                continue
            sid, data = by_dex[dex]
            types = listing(data.get("types")) + ["", ""]
            groups = listing(data.get("egg_groups")) + ["", ""]
            abilities, stats, learnset = section(data, "abilities"), section(data, "base_stats"), section(data, "learnset")
            ev = data.get("ev_yield") if isinstance(data.get("ev_yield"), dict) else {}
            source = evolves_from.get(sid, ("", ""))
            row = [dex, sid, data.get("name"), types[0], types[1], abilities.get("primary"), abilities.get("secondary"),
                   abilities.get("hidden"), dexlib.bst(data)] + [stats.get(s) for s in STATS] + [
                source[0], source[1], data.get("category"), data.get("height_m"), data.get("weight_kg"),
                data.get("body_color"), ", ".join("%s %s" % (v, k) for k, v in ev.items() if v),
                data.get("catch_rate"), data.get("base_exp"), data.get("growth_rate"), data.get("base_friendship"),
                data.get("gender"), groups[0], groups[1], data.get("egg_cycles"),
                section(data, "held_items").get("common"), section(data, "held_items").get("rare"),
                ", ".join("%s (%s)" % (m.get("move"), "evo" if m.get("level") == 0 else m.get("level")) for m in listing(learnset.get("level_up")) if isinstance(m, dict)),
                ", ".join(str(m) for m in listing(learnset.get("tm_hm"))),
                ", ".join(str(m) for m in listing(learnset.get("tutor"))),
                ", ".join(str(m) for m in listing(learnset.get("egg"))),
                "; ".join(" | ".join("" if e.get(k) is None else str(e.get(k)) for k in ("location", "method", "levels", "rate")).rstrip(" |")
                          for e in listing(data.get("encounters")) if isinstance(e, dict)),
                data.get("description"), section(data, "design").get("concept"), section(data, "design").get("name_origin"),
                section(data, "design").get("notes"), section(data, "credits").get("designer"),
                section(data, "credits").get("artist"), dexlib.completeness(data)]
            writer.writerow(["" if value is None else value for value in row])

    # ---- export/sheet.csv (laid out for the Google Sheet: readable headers, a row of hints, total as a formula) ----
    with open(export / "dex.csv", newline="", encoding="utf-8") as handle:
        table = list(csv.reader(handle))
    keep = [i for i, column in enumerate(table[0]) if column not in ("id", "complete_percent")]
    columns = [table[0][i] for i in keep]
    total = columns.index("bst")
    first, last = (chr(ord("A") + columns.index(stat)) for stat in (STATS[0], STATS[-1]))
    with open(export / "sheet.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow([SHEET_COLUMNS[column][0] for column in columns])
        writer.writerow([SHEET_COLUMNS[column][1] for column in columns])   # hints; has no dex number, so it is never imported
        for number, line in enumerate(table[1:], start=3):
            cells = [line[i] for i in keep]
            cells[total] = "=SUM(%s%d:%s%d)" % (first, number, last, number)
            writer.writerow(cells)

    # ---- export/dex.json (everything, for the ROM hack tooling later) ----
    payload = {"config": config, "species": [dict(data, id=sid) for sid, _, data in species]}
    (export / "dex.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print("Built DEX.md, TODO.md, export/dex.csv, export/sheet.csv, export/dex.json (%d species, %d open slots)" % (len(species), len(open_slots)))
    export_expansion.main()
    build_site.main()


if __name__ == "__main__":
    main()
