#!/usr/bin/env python3
"""Generate DEX.md, TODO.md and everything in export/ from data/species/.

These files are generated - never edit them by hand, edit the species files instead.
"""
import csv
import json

import dexlib
import build_site
import export_expansion
from dexlib import ROOT, STATS, section, listing

GENERATED = "<!-- GENERATED by scripts/build.py - do not edit by hand, edit data/species/*.yaml instead -->\n\n"


def evolution_text(evo, names):
    return names.get(evo.get("into"), evo.get("into")), dexlib.evolution_to_text(evo)


def main():
    config = dexlib.load_config()
    dex_size = config.get("dex_size", 100)
    species, problems = dexlib.load_species()
    if problems:
        for path, msg in problems:
            print("ERROR %s: %s" % (path.relative_to(ROOT), msg))
        raise SystemExit("Fix the files above first (run scripts/validate.py).")

    by_dex = {data.get("dex"): (sid, data) for sid, _, data in species}
    names = {sid: data.get("name") for sid, _, data in species}
    evolves_from = {}
    for sid, _, data in species:
        for evo in listing(data.get("evolutions")):
            if isinstance(evo, dict):
                evolves_from[evo.get("into")] = (data.get("name"), evolution_text(evo, names)[1])

    # ---- DEX.md ----
    done = sum(1 for _, _, d in species if dexlib.completeness(d) == 100)
    average = round(sum(dexlib.completeness(d) for _, _, d in species) / len(species)) if species else 0
    lines = [GENERATED, "# %s\n" % config.get("project", "Pokedex"),
             "**%d / %d** slots have a Pokemon - **%d** are fully complete - average completeness **%d%%**.\n"
             % (len(species), dex_size, done, average),
             "What is still missing for each one: [TODO.md](TODO.md)\n",
             "| # | Name | Types | Abilities | BST | Evolves into | Done |",
             "|--:|------|-------|-----------|----:|--------------|-----:|"]
    for dex in range(1, dex_size + 1):
        if dex not in by_dex:
            lines.append("| %d | *open slot* | | | | | |" % dex)
            continue
        sid, data = by_dex[dex]
        abilities = section(data, "abilities")
        ability_names = [str(abilities[k]) + (" (H)" if k == "hidden" else "")
                         for k in ("primary", "secondary", "hidden") if abilities.get(k)]
        evos = ["%s (%s)" % evolution_text(e, names) for e in listing(data.get("evolutions")) if isinstance(e, dict)]
        total = dexlib.bst(data)
        lines.append("| %d | [%s](data/species/%s.yaml) | %s | %s | %s | %s | %d%% |" % (
            dex, data.get("name"), sid, " / ".join(str(t) for t in listing(data.get("types"))),
            ", ".join(ability_names), total if total is not None else "", ", ".join(evos),
            dexlib.completeness(data)))
    (ROOT / "DEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- TODO.md ----
    lines = [GENERATED, "# What is left to do\n",
             "A Pokemon is complete when every item below is filled in. Field guide: [docs/FIELDS.md](docs/FIELDS.md)\n",
             "## Progress per area\n", "| Area | Item | Filled in |", "|------|------|----------:|"]
    for sec, label, test in dexlib.CHECKS:
        count = sum(1 for _, _, d in species if test(d))
        lines.append("| %s | %s | %d / %d |" % (sec, label, count, len(species)))
    open_slots = [str(d) for d in range(1, dex_size + 1) if d not in by_dex]
    lines += ["", "## Open dex slots (%d)\n" % len(open_slots), ", ".join("#" + s for s in open_slots) or "None", "",
              "## Missing per Pokemon\n"]
    for sid, _, data in species:
        gaps = dexlib.missing(data)
        if not gaps:
            continue
        lines.append("### #%s [%s](data/species/%s.yaml) - %d%%\n" % (data.get("dex"), data.get("name"), sid, dexlib.completeness(data)))
        for sec in dexlib.SECTIONS:
            labels = [label for s, label in gaps if s == sec]
            if labels:
                lines.append("- **%s:** %s" % (sec, ", ".join(labels)))
        lines.append("")
    (ROOT / "TODO.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- export/dex.csv (one row per slot, opens in Google Sheets / Excel) ----
    export = ROOT / "export"
    export.mkdir(exist_ok=True)
    header = ["dex", "id", "name", "type_1", "type_2", "ability_1", "ability_2", "hidden_ability", "bst"] + STATS + [
        "evolves_from", "evo_condition", "category", "height_m", "weight_kg", "body_color", "ev_yield", "catch_rate",
        "base_exp", "growth_rate", "base_friendship", "gender", "egg_group_1", "egg_group_2", "egg_cycles",
        "held_item_common", "held_item_rare", "level_up_moves", "tm_hm_moves", "tutor_moves", "egg_moves",
        "encounters", "description", "concept", "name_origin", "notes", "designer", "artist", "complete_percent"]
    with open(export / "dex.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        for dex in range(1, dex_size + 1):
            if dex not in by_dex:
                writer.writerow([dex] + [""] * (len(header) - 1))
                continue
            sid, data = by_dex[dex]
            types = listing(data.get("types")) + ["", ""]
            groups = listing(data.get("egg_groups")) + ["", ""]
            abilities, stats, learnset = section(data, "abilities"), section(data, "base_stats"), section(data, "learnset")
            ev = data.get("ev_yield") if isinstance(data.get("ev_yield"), dict) else {}
            source = evolves_from.get(sid, ("", ""))
            row = [dex, sid, data.get("name"), types[0], types[1], abilities.get("primary"), abilities.get("secondary"),
                   abilities.get("hidden"), dexlib.bst(data)] + [stats.get(s) for s in STATS] + [
                source[0], source[1], data.get("category"), data.get("height_m"), data.get("weight_kg"),
                data.get("body_color"), ", ".join("%s %s" % (v, k) for k, v in ev.items() if v),
                data.get("catch_rate"), data.get("base_exp"), data.get("growth_rate"), data.get("base_friendship"),
                data.get("gender"), groups[0], groups[1], data.get("egg_cycles"),
                section(data, "held_items").get("common"), section(data, "held_items").get("rare"),
                ", ".join("%s (%s)" % (m.get("move"), m.get("level")) for m in listing(learnset.get("level_up")) if isinstance(m, dict)),
                ", ".join(str(m) for m in listing(learnset.get("tm_hm"))),
                ", ".join(str(m) for m in listing(learnset.get("tutor"))),
                ", ".join(str(m) for m in listing(learnset.get("egg"))),
                "; ".join(" | ".join("" if e.get(k) is None else str(e.get(k)) for k in ("location", "method", "levels", "rate")).rstrip(" |")
                          for e in listing(data.get("encounters")) if isinstance(e, dict)),
                data.get("description"), section(data, "design").get("concept"), section(data, "design").get("name_origin"),
                section(data, "design").get("notes"), section(data, "credits").get("designer"),
                section(data, "credits").get("artist"), dexlib.completeness(data)]
            writer.writerow(["" if value is None else value for value in row])

    # ---- export/sheet.csv (dex.csv laid out for the Google Sheet: no internal columns, total as a formula) ----
    with open(export / "dex.csv", newline="", encoding="utf-8") as handle:
        table = list(csv.reader(handle))
    keep = [i for i, column in enumerate(table[0]) if column not in ("id", "complete_percent")]
    total = [table[0][i] for i in keep].index("bst")
    first, last = (chr(ord("A") + [table[0][i] for i in keep].index(stat)) for stat in (STATS[0], STATS[-1]))
    with open(export / "sheet.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        for number, line in enumerate(table, start=1):
            cells = [line[i] for i in keep]
            if number > 1:
                cells[total] = "=SUM(%s%d:%s%d)" % (first, number, last, number)
            writer.writerow(cells)

    # ---- export/dex.json (everything, for the ROM hack tooling later) ----
    payload = {"config": config, "species": [dict(data, id=sid) for sid, _, data in species]}
    (export / "dex.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print("Built DEX.md, TODO.md, export/dex.csv, export/sheet.csv, export/dex.json (%d species, %d open slots)" % (len(species), len(open_slots)))
    export_expansion.main()
    build_site.main()


if __name__ == "__main__":
    main()
