#!/usr/bin/env python3
"""Write every species in the C format of VANILLA Emerald (pret/pokeemerald), into export/engine/.

NOTE: the project has since chosen pokeemerald-expansion as its base, which stores species
differently. This exporter still produces the vanilla layout used for the first proof of
concept and will be replaced by an expansion exporter (see docs/ENGINE.md).

Each output file is named after the file in the game's source it belongs in (see
docs/ENGINE.md). Values that are not filled in yet come out as TODO comments, so the
output only compiles once a species is complete.
"""
import re
import textwrap

import dexlib
from dexlib import ROOT, constant, section, listing

OUT = ROOT / "export" / "engine"
HEADER = "// GENERATED by scripts/export_engine.py from data/species/ - do not edit by hand.\n// Goes into: %s\n\n"


def todo(what):
    return "0 /* TODO: %s */" % what


def ident(name):
    """'Giga-Circuit' -> 'GigaCircuit', used in C variable names."""
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", str(name)) if part)


def folder(name):
    return constant(name).lower()


def number(value, what):
    return str(value) if value is not None else todo(what)


def gender(value):
    if value is None:
        return todo("gender")
    if value == "genderless":
        return "MON_GENDERLESS"
    if value == 100:
        return "MON_MALE"
    if value == 0:
        return "MON_FEMALE"
    return "PERCENT_FEMALE(%s)" % ("%g" % (100 - value))


def pair(values, prefix, what, rename=None):
    values = [(rename or {}).get(v, v) for v in values]
    if not values:
        return "{ %s }" % todo(what)
    values = (values + values)[:2]
    return "{ %s }" % ", ".join(prefix + constant(v) for v in values)


def species_info(data):
    stats, ev, abilities = section(data, "base_stats"), data.get("ev_yield"), section(data, "abilities")
    ev = ev if isinstance(ev, dict) else None
    items, engine = section(data, "held_items"), section(data, "engine")
    ability_list = [abilities.get("primary") or None, abilities.get("secondary") or None]
    ability_text = ", ".join("ABILITY_" + constant(a) if a else "ABILITY_NONE" for a in ability_list)
    rows = [
        (".baseHP", number(stats.get("hp"), "hp")),
        (".baseAttack", number(stats.get("attack"), "attack")),
        (".baseDefense", number(stats.get("defense"), "defense")),
        (".baseSpeed", number(stats.get("speed"), "speed")),
        (".baseSpAttack", number(stats.get("sp_attack"), "sp_attack")),
        (".baseSpDefense", number(stats.get("sp_defense"), "sp_defense")),
        (".types", pair(listing(data.get("types")), "TYPE_", "types")),
        (".catchRate", number(data.get("catch_rate"), "catch_rate")),
        (".expYield", number(data.get("base_exp"), "base_exp")),
    ]
    for field, stat in ((".evYield_HP", "hp"), (".evYield_Attack", "attack"), (".evYield_Defense", "defense"),
                        (".evYield_Speed", "speed"), (".evYield_SpAttack", "sp_attack"), (".evYield_SpDefense", "sp_defense")):
        rows.append((field, str(ev.get(stat, 0)) if ev is not None else todo("ev_yield")))
    rows += [
        (".itemCommon", "ITEM_" + constant(items["common"]) if items.get("common") else "ITEM_NONE"),
        (".itemRare", "ITEM_" + constant(items["rare"]) if items.get("rare") else "ITEM_NONE"),
        (".genderRatio", gender(data.get("gender"))),
        (".eggCycles", number(data.get("egg_cycles"), "egg_cycles")),
        (".friendship", "STANDARD_FRIENDSHIP" if data.get("base_friendship") == 70 else number(data.get("base_friendship"), "base_friendship")),
        (".growthRate", "GROWTH_" + constant(data["growth_rate"]) if data.get("growth_rate") else todo("growth_rate")),
        (".eggGroups", pair(listing(data.get("egg_groups")), "EGG_GROUP_", "egg_groups", {"undiscovered": "no_eggs_discovered"})),
        (".abilities", "{%s}" % ability_text if ability_list[0] else "{ %s }" % todo("abilities")),
        (".safariZoneFleeRate", str(engine.get("safari_flee_rate") or 0)),
        (".bodyColor", "BODY_COLOR_" + constant(data["body_color"]) if data.get("body_color") else todo("body_color")),
        (".noFlip", "TRUE" if engine.get("no_flip") else "FALSE"),
    ]
    body = "".join("        %s = %s,\n" % row for row in rows)
    return "    [SPECIES_%s] =\n    {\n%s    },\n\n" % (constant(data.get("name")), body)


def evolution(data, names):
    entries = []
    for evo in listing(data.get("evolutions")):
        method = dexlib.EVOLUTION_METHODS.get(evo.get("method"))
        target = "SPECIES_" + constant(names.get(evo.get("into"), evo.get("into")))
        if method is None:
            entries.append("/* TODO custom evolution into %s: %s */" % (target, evo.get("note")))
            continue
        if evo.get("method") in dexlib.ITEM_METHODS:
            param = "ITEM_" + constant(evo.get("item"))
        elif evo.get("method") in dexlib.LEVEL_METHODS or evo.get("method") == "beauty":
            param = str(evo.get("level") or todo("value"))
        else:
            param = "0"
        entries.append("{%s, %s, %s}" % (method, param, target))
    if not entries:
        return ""
    return "    [SPECIES_%s] = {%s},\n" % (constant(data.get("name")), ",\n        ".join(entries))


def dex_text(data):
    text = data.get("description")
    if not text:
        lines = ["TODO: description"]
    else:
        lines = text.strip().split("\n")
        if len(lines) == 1:
            lines = textwrap.wrap(lines[0], dexlib.DESCRIPTION_LINE_LENGTH - 2)
    quoted = ['    "%s%s"' % (line.strip().replace('"', '\\"'), "\\n" if i < len(lines) - 1 else "") for i, line in enumerate(lines)]
    return "const u8 g%sPokedexText[] = _(\n%s);\n\n" % (ident(data.get("name")), "\n".join(quoted))


def dex_entry(data):
    name = data.get("name")
    height, weight = data.get("height_m"), data.get("weight_kg")
    rows = [
        (".categoryName", '_("%s")' % str(data.get("category") or "TODO").upper()),
        (".height", str(round(height * 10)) if height is not None else todo("height_m")),
        (".weight", str(round(weight * 10)) if weight is not None else todo("weight_kg")),
        (".description", "g%sPokedexText" % ident(name)),
        (".pokemonScale", "256"), (".pokemonOffset", "0"), (".trainerScale", "256"), (".trainerOffset", "0"),
    ]
    body = "".join("        %s = %s,\n" % row for row in rows)
    return "    [NATIONAL_DEX_%s] =\n    {\n%s    },\n\n" % (constant(name), body)


def main():
    species, problems = dexlib.load_species()
    if problems:
        raise SystemExit("Fix the species files first (run scripts/validate.py).")
    engine = dexlib.load_engine()
    names = {sid: data.get("name") for sid, _, data in species}
    all_data = [data for _, _, data in species]
    OUT.mkdir(parents=True, exist_ok=True)
    files = {}

    def add(filename, target, text):
        files[filename] = HEADER % target + text

    add("species.h", "include/constants/species.h (numbers get assigned when the species are added to the game)",
        "".join("#define SPECIES_%-16s /* Sigma dex #%s */\n" % (constant(d.get("name")), d.get("dex")) for d in all_data))
    add("pokedex.h", "include/constants/pokedex.h (the dex order enum)",
        "".join("    NATIONAL_DEX_%s,\n" % constant(d.get("name")) for d in all_data))
    add("species_names.h", "src/data/text/species_names.h (max %d characters each)" % dexlib.NAME_LIMIT,
        "".join('    [SPECIES_%s] = _("%s"),\n' % (constant(d.get("name")), str(d.get("name")).upper()) for d in all_data))
    add("species_info.h", "src/data/pokemon/species_info.h", "".join(species_info(d) for d in all_data))
    add("evolution.h", "src/data/pokemon/evolution.h", "".join(evolution(d, names) for d in all_data))
    add("pokedex_text.h", "src/data/pokemon/pokedex_text.h", "".join(dex_text(d) for d in all_data))
    add("pokedex_entries.h", "src/data/pokemon/pokedex_entries.h", "".join(dex_entry(d) for d in all_data))

    learnsets, pointers, tmhm, tutor, eggs, graphics, coords = [], [], [], [], [], [], []
    for data in all_data:
        name, const, var = data.get("name"), constant(data.get("name")), ident(data.get("name"))
        learnset, details = section(data, "learnset"), section(data, "engine")
        moves = sorted((m for m in listing(learnset.get("level_up")) if isinstance(m, dict)), key=lambda m: m.get("level", 0))
        rows = "".join("    LEVEL_UP_MOVE(%2s, MOVE_%s),\n" % (m.get("level"), constant(m.get("move"))) for m in moves)
        learnsets.append("static const u16 s%sLevelUpLearnset[] = {\n%s    LEVEL_UP_END\n};\n\n" % (var, rows or "    /* TODO: level-up moves */\n"))
        pointers.append("    [SPECIES_%s] = s%sLevelUpLearnset,\n" % (const, var))
        known = {dexlib.norm(m) for m in listing(learnset.get("tm_hm"))}
        rows = "".join("        .%s = TRUE,\n" % constant(m) for m in engine["tm_hm_order"] if dexlib.norm(m) in known)
        tmhm.append("    [SPECIES_%s] = { .learnset = {\n%s    } },\n\n" % (const, rows))
        tutor_moves = listing(learnset.get("tutor"))
        tutor.append("    [SPECIES_%s] = (%s),\n" % (const, "\n        | ".join("TUTOR(MOVE_%s)" % constant(m) for m in tutor_moves) or "0"))
        egg_moves = listing(learnset.get("egg"))
        if egg_moves:
            eggs.append("    egg_moves(%s,\n%s),\n\n" % (const, ",\n".join("              MOVE_%s" % constant(m) for m in egg_moves)))
        path = "graphics/pokemon/%s" % folder(name)
        graphics.append(
            'const u32 gMonStillFrontPic_%(v)s[] = INCGFX_U32("%(p)s/front.png", ".4bpp.lz");\n'
            'const u32 gMonFrontPic_%(v)s[] = INCGFX_U32("%(p)s/anim_front.png", ".4bpp.lz");\n'
            'const u32 gMonPalette_%(v)s[] = INCGFX_U32("%(p)s/normal.pal", ".gbapal.lz");\n'
            'const u32 gMonBackPic_%(v)s[] = INCGFX_U32("%(p)s/back.png", ".4bpp.lz");\n'
            'const u32 gMonShinyPalette_%(v)s[] = INCGFX_U32("%(p)s/shiny.pal", ".gbapal.lz");\n'
            'const u8 gMonIcon_%(v)s[] = INCGFX_U8("%(p)s/icon.png", ".4bpp");\n'
            'const u8 gMonFootprint_%(v)s[] = INCGFX_U8("%(p)s/footprint.png", ".1bpp");\n\n' % {"v": var, "p": path})
        coords.append("    [SPECIES_%-16s front y_offset = %s, back y_offset = %s, elevation = %s, icon palette = %s\n" % (
            const + "]", number(details.get("front_y_offset"), "front_y_offset"), number(details.get("back_y_offset"), "back_y_offset"),
            details.get("elevation") or 0, number(details.get("icon_palette"), "icon_palette")))

    add("level_up_learnsets.h", "src/data/pokemon/level_up_learnsets.h", "".join(learnsets))
    add("level_up_learnset_pointers.h", "src/data/pokemon/level_up_learnset_pointers.h", "".join(pointers))
    add("tmhm_learnsets.h", "src/data/pokemon/tmhm_learnsets.h", "".join(tmhm))
    add("tutor_learnsets.h", "src/data/pokemon/tutor_learnsets.h", "".join(tutor))
    add("egg_moves.h", "src/data/pokemon/egg_moves.h", "".join(eggs))
    add("graphics.h", "src/data/graphics/pokemon.h (and the image files into graphics/pokemon/<name>/)", "".join(graphics))
    add("sprite_layout.txt", "src/data/pokemon_graphics/*_pic_coordinates.h, enemy_mon_elevation.h and src/pokemon_icon.c (values to copy in by hand)", "".join(coords))

    for stale in OUT.glob("*"):
        if stale.name not in files:
            stale.unlink()
    for filename, text in files.items():
        (OUT / filename).write_text(text, encoding="utf-8")
    print("Wrote %d engine files to export/engine/" % len(files))


if __name__ == "__main__":
    main()
