#!/usr/bin/env python3
"""Write the dex as source code for pokeemerald-expansion, into export/expansion/.

Only Pokemon that are far enough along to exist in a game are written (base stats, a type,
an ability and at least one level-up move); the rest are listed in NOT_READY.md. Whatever a
ready Pokemon still lacks gets a neutral default, and sprites and cry use the game's
question-mark placeholders. scripts/apply_to_expansion.py puts the files into a checkout
of the game.
"""
import textwrap

import dexlib
from dexlib import ROOT, STATS, constant, norm, section, listing

OUT = ROOT / "export" / "expansion"
HEADER = "// GENERATED by scripts/export_expansion.py from the Sigma dex - do not edit by hand.\n\n"
STAT_FIELDS = (("hp", "HP"), ("attack", "Attack"), ("defense", "Defense"), ("speed", "Speed"),
               ("sp_attack", "SpAttack"), ("sp_defense", "SpDefense"))


def ident(name):
    """'Giga-Circuit' -> 'GigaCircuit', used in C variable names."""
    import re
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", str(name)) if part)


class Names:
    """Turns move and ability names into the game's constants; knows which ones do not exist yet."""

    def __init__(self, engine):
        self.constants = engine["constants"]
        self.custom = {}
        for kind, prefix in (("moves", "MOVE_"), ("abilities", "ABILITY_")):
            for entry in engine["custom"][kind]:
                self.custom[norm(entry["name"])] = (prefix + constant(entry["name"]), bool(entry.get("implemented")))

    def get(self, name):
        """(constant, usable). Unknown names and custom ones that are not programmed yet are not usable."""
        key = norm(name)
        if key in self.constants:
            return self.constants[key], True
        if key in self.custom:
            return self.custom[key]
        return None, False


def not_ready(data, names):
    reasons = []
    if dexlib.bst(data) is None:
        reasons.append("base stats")
    types = listing(data.get("types"))
    if not types or any(t not in dexlib.TYPES for t in types):
        reasons.append("a valid type")
    primary = section(data, "abilities").get("primary")
    if not primary or not names.get(primary)[1]:
        reasons.append("an ability that exists in the game")
    moves = [m for m in listing(section(data, "learnset").get("level_up")) if isinstance(m, dict) and names.get(m.get("move"))[1]]
    if not moves:
        reasons.append("a level-up move that exists in the game")
    if len(str(data.get("name") or "")) > dexlib.NAME_LIMIT:
        reasons.append("a name of at most %d letters" % dexlib.NAME_LIMIT)
    return reasons


def gender(value):
    if value == "genderless":
        return "MON_GENDERLESS"
    if value == 100:
        return "MON_MALE"
    if value == 0:
        return "MON_FEMALE"
    return "PERCENT_FEMALE(%g)" % (100 - (50 if value is None else value))


def evolution(evo, target):
    method, level, item = evo.get("method"), evo.get("level"), "ITEM_" + constant(evo.get("item") or "none")
    simple = {
        "level": "{EVO_LEVEL, %s, %s}" % (level, target),
        "item": "{EVO_ITEM, %s, %s}" % (item, target),
        "trade": "{EVO_TRADE, 0, %s}" % target,
        "trade_item": "{EVO_TRADE, 0, %s, CONDITIONS({IF_HOLD_ITEM, %s})}" % (target, item),
        "friendship": "{EVO_LEVEL, 0, %s, CONDITIONS({IF_MIN_FRIENDSHIP, FRIENDSHIP_EVO_THRESHOLD})}" % target,
        "friendship_day": "{EVO_LEVEL, 0, %s, CONDITIONS({IF_MIN_FRIENDSHIP, FRIENDSHIP_EVO_THRESHOLD}, {IF_NOT_TIME, TIME_NIGHT})}" % target,
        "friendship_night": "{EVO_LEVEL, 0, %s, CONDITIONS({IF_MIN_FRIENDSHIP, FRIENDSHIP_EVO_THRESHOLD}, {IF_TIME, TIME_NIGHT})}" % target,
        "level_attack_higher": "{EVO_LEVEL, %s, %s, CONDITIONS({IF_ATK_GT_DEF})}" % (level, target),
        "level_attack_equal": "{EVO_LEVEL, %s, %s, CONDITIONS({IF_ATK_EQ_DEF})}" % (level, target),
        "level_defense_higher": "{EVO_LEVEL, %s, %s, CONDITIONS({IF_ATK_LT_DEF})}" % (level, target),
        "beauty": "{EVO_LEVEL, 0, %s, CONDITIONS({IF_MIN_BEAUTY, %s})}" % (target, level),
    }
    return simple.get(method)


def species_block(data, ready_ids, id_names, names, notes):
    name, const, var = data["name"], constant(data["name"]), ident(data["name"])
    stats, ev, abilities = section(data, "base_stats"), data.get("ev_yield"), section(data, "abilities")
    items, engine, learnset = section(data, "held_items"), section(data, "engine"), section(data, "learnset")
    rows = [(".base%s" % field, str(stats[key])) for key, field in STAT_FIELDS]
    rows.append((".types", "MON_TYPES(%s)" % ", ".join("TYPE_" + constant(t) for t in listing(data.get("types")))))
    rows.append((".catchRate", str(data.get("catch_rate") or 45)))
    rows.append((".expYield", str(data.get("base_exp") or 64)))
    for key, field in STAT_FIELDS:
        if isinstance(ev, dict) and ev.get(key):
            rows.append((".evYield_%s" % field, str(ev[key])))
    for key, field in (("common", ".itemCommon"), ("rare", ".itemRare")):
        if items.get(key):
            rows.append((field, "ITEM_" + constant(items[key])))
    groups = [g for g in listing(data.get("egg_groups"))] or ["undiscovered"]
    slots = []
    for slot in ("primary", "secondary", "hidden"):
        ability = abilities.get(slot)
        const_name, usable = names.get(ability) if ability else (None, False)
        if ability and not usable:
            notes.append("%s: ability '%s' is not in the game yet, left out" % (name, ability))
        slots.append(const_name if usable else "ABILITY_NONE")
    rows += [
        (".genderRatio", gender(data.get("gender"))),
        (".eggCycles", str(data.get("egg_cycles") or 20)),
        (".friendship", "STANDARD_FRIENDSHIP" if data.get("base_friendship") in (None, 70) else str(data["base_friendship"])),
        (".growthRate", "GROWTH_" + constant(data.get("growth_rate") or "medium_fast")),
        (".eggGroups", "MON_EGG_GROUPS(%s)" % ", ".join(
            "EGG_GROUP_" + constant("no_eggs_discovered" if g == "undiscovered" else g) for g in groups)),
        (".abilities", "{ %s }" % ", ".join(slots)),
        (".bodyColor", "BODY_COLOR_" + constant(data.get("body_color") or "gray")),
    ]
    if engine.get("no_flip"):
        rows.append((".noFlip", "TRUE"))
    description = data.get("description")
    if description:
        lines = description.strip().split("\n")
        if len(lines) == 1:
            lines = textwrap.wrap(lines[0], dexlib.DESCRIPTION_LINE_LENGTH - 2)
    else:
        lines = ["This Pokemon has no Pokedex entry yet."]
    quoted = ["            \"%s%s\"" % (line.strip().replace("\\", "\\\\").replace('"', '\\"'), "\\n" if i < len(lines) - 1 else "")
              for i, line in enumerate(lines[:dexlib.DESCRIPTION_LINES])]
    height, weight = data.get("height_m"), data.get("weight_kg")
    rows += [
        (".speciesName", '_("%s")' % name),
        (".cryId", "CRY_NONE"),
        (".natDexNum", "NATIONAL_DEX_" + const),
        (".categoryName", '_("%s")' % (data.get("category") or "Unknown")),
        (".height", str(round(height * 10)) if height else "0"),
        (".weight", str(round(weight * 10)) if weight else "0"),
        (".description", "COMPOUND_STRING(\n%s)" % "\n".join(quoted)),
        (".pokemonScale", "256"), (".pokemonOffset", "0"), (".trainerScale", "256"), (".trainerOffset", "0"),
        # Placeholder art until this Pokemon has sprites.
        (".frontPic", "gMonFrontPic_CircledQuestionMark"), (".frontPicSize", "MON_COORDS_SIZE(64, 64)"),
        (".frontPicYOffset", str(engine.get("front_y_offset") or 0)), (".frontAnimFrames", "sAnims_SingleFramePlaceHolder"),
        (".backPic", "gMonBackPic_CircledQuestionMark"), (".backPicSize", "MON_COORDS_SIZE(64, 64)"),
        (".backPicYOffset", str(engine.get("back_y_offset") if engine.get("back_y_offset") is not None else 7)),
        (".backAnimId", "BACK_ANIM_NONE"),
        (".palette", "gMonPalette_CircledQuestionMark"), (".shinyPalette", "gMonShinyPalette_CircledQuestionMark"),
        (".iconSprite", "gMonIcon_QuestionMark"), (".iconPalIndex", str(engine.get("icon_palette") or 0)),
    ]
    if engine.get("elevation"):
        rows.append((".enemyMonElevation", str(engine["elevation"])))
    rows.append((".levelUpLearnset", "s%sLevelUpLearnset" % var))
    rows.append((".teachableLearnset", "s%sTeachableLearnset" % var))
    if usable_moves(learnset.get("egg"), names, name, notes):
        rows.append((".eggMoveLearnset", "s%sEggMoveLearnset" % var))
    evolutions = []
    for evo in listing(data.get("evolutions")):
        if not isinstance(evo, dict):
            continue
        if evo.get("into") not in ready_ids:
            notes.append("%s: evolution into %s left out until that Pokemon is ready" % (name, id_names.get(evo.get("into"), evo.get("into"))))
            continue
        text = evolution(evo, "SPECIES_" + constant(id_names[evo["into"]]))
        if text is None:
            notes.append("%s: evolution into %s needs custom code (%s)" % (name, id_names[evo["into"]], evo.get("note")))
            continue
        evolutions.append(text)
    if evolutions:
        rows.append((".evolutions", "EVOLUTION(%s)" % (",\n" + " " * 32).join(evolutions)))
    body = "".join("        %s = %s,\n" % row for row in rows)
    return "    [SPECIES_%s] =\n    {\n%s        FOOTPRINT(QuestionMark)\n    },\n\n" % (const, body)


def usable_moves(moves, names, owner, notes):
    out = []
    for move in listing(moves):
        const_name, usable = names.get(move)
        if usable and const_name not in out:
            out.append(const_name)
        elif not usable:
            notes.append("%s: move '%s' is not in the game yet, left out" % (owner, move))
    return out


def main():
    species, problems = dexlib.load_species()
    if problems:
        raise SystemExit("Fix the species files first (run scripts/validate.py).")
    engine = dexlib.load_engine()
    names = Names(engine)
    id_names = {sid: data.get("name") for sid, _, data in species}
    ready, waiting, notes = [], [], []
    for sid, _, data in species:
        reasons = not_ready(data, names)
        (waiting if reasons else ready).append((sid, data, reasons))
    ready_ids = {sid for sid, _, _ in ready}

    info, level_up, teachable, egg, tests = [], [], [], [], []
    for sid, data, _ in ready:
        name, const, var = data["name"], constant(data["name"]), ident(data["name"])
        learnset = section(data, "learnset")
        info.append(species_block(data, ready_ids, id_names, names, notes))
        moves = sorted((m for m in listing(learnset.get("level_up")) if isinstance(m, dict)), key=lambda m: m.get("level", 0))
        rows, first_move = [], None
        for move in moves:
            const_name, usable = names.get(move.get("move"))
            if not usable:
                notes.append("%s: move '%s' is not in the game yet, left out" % (name, move.get("move")))
                continue
            first_move = first_move or const_name
            rows.append("    LEVEL_UP_MOVE(%2s, %s),\n" % (move.get("level"), const_name))
        level_up.append("static const struct LevelUpMove s%sLevelUpLearnset[] = {\n%s    LEVEL_UP_END\n};\n\n" % (var, "".join(rows)))
        taught = usable_moves(listing(learnset.get("tm_hm")) + listing(learnset.get("tutor")), names, name, notes)
        teachable.append("static const u16 s%sTeachableLearnset[] = {\n%s    MOVE_UNAVAILABLE,\n};\n\n" % (var, "".join("    %s,\n" % m for m in taught)))
        egg_moves = usable_moves(learnset.get("egg"), names, name, [])
        if egg_moves:
            egg.append("static const u16 s%sEggMoveLearnset[] = {\n%s    MOVE_UNAVAILABLE,\n};\n\n" % (var, "".join("    %s,\n" % m for m in egg_moves)))
        stats = section(data, "base_stats")
        checks = ["    EXPECT_EQ(info->base%s, %d);\n" % (field, stats[key]) for key, field in STAT_FIELDS]
        types = listing(data.get("types"))
        checks.append("    EXPECT_EQ(info->types[0], TYPE_%s);\n" % constant(types[0]))
        checks.append("    EXPECT_EQ(info->types[1], TYPE_%s);\n" % constant(types[-1]))
        checks.append("    EXPECT_EQ(info->abilities[0], %s);\n" % names.get(section(data, "abilities")["primary"])[0])
        checks.append("    EXPECT_EQ(info->levelUpLearnset[0].move, %s);\n" % first_move)
        checks.append("    EXPECT_EQ(GetSpeciesName(SPECIES_%s)[0], CHAR_%s);\n" % (const, name[0].upper()) if name[0].isalpha() else "")
        tests.append('TEST("Sigma dex: %s has the data from its species file")\n{\n    const struct SpeciesInfo *info = &gSpeciesInfo[SPECIES_%s];\n%s}\n\n'
                     % (name, const, "".join(checks)))
        tests.append('SINGLE_BATTLE_TEST("Sigma dex: %s can use its first move in battle")\n{\n    GIVEN {\n        PLAYER(SPECIES_%s) { Moves(%s); }\n'
                     '        OPPONENT(SPECIES_WOBBUFFET);\n    } WHEN {\n        TURN { MOVE(player, %s); }\n    } SCENE {\n'
                     '        ANIMATION(ANIM_TYPE_MOVE, %s, player);\n    }\n}\n\n' % (name, const, first_move, first_move, first_move))

    files = {
        "species_enum.h": HEADER + "".join("    SPECIES_%s,\n" % constant(d["name"]) for _, d, _ in ready),
        "pokedex_enum.h": HEADER + "".join("    NATIONAL_DEX_%s,\n" % constant(d["name"]) for _, d, _ in ready),
        "species_info.h": HEADER + "".join(info),
        "level_up_learnsets.h": HEADER + "".join(level_up),
        "teachable_learnsets.h": HEADER + "".join(teachable),
        "egg_moves.h": HEADER + "".join(egg),
        "sigma_dex_test.c": HEADER + '#include "global.h"\n#include "pokemon.h"\n#include "test/battle.h"\n#include "constants/characters.h"\n\n' + "".join(tests),
        "NOT_READY.md": "<!-- GENERATED by scripts/export_expansion.py -->\n\n# Game export status\n\n"
                        "**%d** Pokemon are written as game code: %s\n\n"
                        "## Not exported yet (%d)\n\nA Pokemon is exported once it has base stats, a valid type, an ability and a level-up move.\n\n%s\n"
                        "## Left out of exported Pokemon\n\n%s\n" % (
                            len(ready), ", ".join(d["name"] for _, d, _ in ready) or "none", len(waiting),
                            "".join("- **%s** needs: %s\n" % (d.get("name"), ", ".join(r)) for _, d, r in waiting),
                            "".join("- %s\n" % n for n in sorted(set(notes))) or "Nothing.\n"),
    }
    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("*"):
        if stale.name not in files:
            stale.unlink()
    for filename, text in files.items():
        (OUT / filename).write_text(text, encoding="utf-8")
    print("Wrote game code for %d Pokemon to export/expansion/ (%d not ready yet)" % (len(ready), len(waiting)))


if __name__ == "__main__":
    main()
